version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: v1-venv-{{ checksum "setup.py" }}
      - run:
          name: Install dependencies.
          command: |
            sudo pip install .
            sudo pip install .[devel]
      - save_cache:
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
          key: v1-venv-{{ checksum "setup.py" }}
          when: on_success
      - run:
          name: Make additional files for the tests.
          command: |
            touch lychee/converters/inbound/tests/__init__.py
            touch lychee/converters/outbound/tests/__init__.py
            mkdir -p test_results/junit
      - run:
          name: Run the tests.
          command: py.test --cov=lychee --junit-xml=test_results/junit/junit.xml
      - store_test-results:
          path: test_results
