version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: |
            sudo pip install .
            sudo pip install .[devel]
      - run:
          name: Make additional files for the tests.
          command: |
            touch lychee/converters/inbound/tests/__init__.py
            touch lychee/converters/outbound/tests/__init__.py
            mkdir -p test_results/junit
      - run:
          name: Run the tests.
          command: py.test --cov=lychee --junit-xml=test_results/junit/junit.xml
      - store_test-results:
          path: test_results
