# -*- coding: utf-8 -*-
'''
Contains dictionaries for translating LilyPond pitch names to
MEI pitch names and back in all languages. This file is generated
by lychee/scripts/make_lilypond_note_names.py.
'''
inbound = {
    u'catalan': {
        u'do': ('c', ''),
        u'dob': ('c', 'f'),
        u'dobb': ('c', 'ff'),
        u'dod': ('c', 's'),
        u'dodd': ('c', 'x'),
        u'dos': ('c', 's'),
        u'doss': ('c', 'x'),
        u'fa': ('f', ''),
        u'fab': ('f', 'f'),
        u'fabb': ('f', 'ff'),
        u'fad': ('f', 's'),
        u'fadd': ('f', 'x'),
        u'fas': ('f', 's'),
        u'fass': ('f', 'x'),
        u'la': ('a', ''),
        u'lab': ('a', 'f'),
        u'labb': ('a', 'ff'),
        u'lad': ('a', 's'),
        u'ladd': ('a', 'x'),
        u'las': ('a', 's'),
        u'lass': ('a', 'x'),
        u'mi': ('e', ''),
        u'mib': ('e', 'f'),
        u'mibb': ('e', 'ff'),
        u'mid': ('e', 's'),
        u'midd': ('e', 'x'),
        u'mis': ('e', 's'),
        u'miss': ('e', 'x'),
        u're': ('d', ''),
        u'reb': ('d', 'f'),
        u'rebb': ('d', 'ff'),
        u'red': ('d', 's'),
        u'redd': ('d', 'x'),
        u'res': ('d', 's'),
        u'ress': ('d', 'x'),
        u'si': ('b', ''),
        u'sib': ('b', 'f'),
        u'sibb': ('b', 'ff'),
        u'sid': ('b', 's'),
        u'sidd': ('b', 'x'),
        u'sis': ('b', 's'),
        u'siss': ('b', 'x'),
        u'sol': ('g', ''),
        u'solb': ('g', 'f'),
        u'solbb': ('g', 'ff'),
        u'sold': ('g', 's'),
        u'soldd': ('g', 'x'),
        u'sols': ('g', 's'),
        u'solss': ('g', 'x'),
        },
    u'deutsch': {
        u'a': ('a', ''),
        u'aeh': ('a', '1qf'),
        u'aih': ('a', '1qs'),
        u'ais': ('a', 's'),
        u'aisih': ('a', '3qs'),
        u'aisis': ('a', 'x'),
        u'as': ('a', 'f'),
        u'asah': ('a', '3qf'),
        u'asas': ('a', 'ff'),
        u'aseh': ('a', '3qf'),
        u'ases': ('a', 'ff'),
        u'b': ('b', 'f'),
        u'beh': ('b', '1qf'),
        u'c': ('c', ''),
        u'ceh': ('c', '1qf'),
        u'ces': ('c', 'f'),
        u'ceseh': ('c', '3qf'),
        u'ceses': ('c', 'ff'),
        u'cih': ('c', '1qs'),
        u'cis': ('c', 's'),
        u'cisih': ('c', '3qs'),
        u'cisis': ('c', 'x'),
        u'd': ('d', ''),
        u'deh': ('d', '1qf'),
        u'des': ('d', 'f'),
        u'deseh': ('d', '3qf'),
        u'deses': ('d', 'ff'),
        u'dih': ('d', '1qs'),
        u'dis': ('d', 's'),
        u'disih': ('d', '3qs'),
        u'disis': ('d', 'x'),
        u'e': ('e', ''),
        u'eeh': ('e', '1qf'),
        u'eih': ('e', '1qs'),
        u'eis': ('e', 's'),
        u'eisih': ('e', '3qs'),
        u'eisis': ('e', 'x'),
        u'es': ('e', 'f'),
        u'eseh': ('e', '3qf'),
        u'eses': ('e', 'ff'),
        u'f': ('f', ''),
        u'feh': ('f', '1qf'),
        u'fes': ('f', 'f'),
        u'feseh': ('f', '3qf'),
        u'feses': ('f', 'ff'),
        u'fih': ('f', '1qs'),
        u'fis': ('f', 's'),
        u'fisih': ('f', '3qs'),
        u'fisis': ('f', 'x'),
        u'g': ('g', ''),
        u'geh': ('g', '1qf'),
        u'ges': ('g', 'f'),
        u'geseh': ('g', '3qf'),
        u'geses': ('g', 'ff'),
        u'gih': ('g', '1qs'),
        u'gis': ('g', 's'),
        u'gisih': ('g', '3qs'),
        u'gisis': ('g', 'x'),
        u'h': ('b', ''),
        u'heseh': ('b', '3qf'),
        u'heses': ('b', 'ff'),
        u'hih': ('b', '1qs'),
        u'his': ('b', 's'),
        u'hisih': ('b', '3qs'),
        u'hisis': ('b', 'x'),
        },
    u'english': {
        u'a': ('a', ''),
        u'a-flat': ('a', 'f'),
        u'a-flatflat': ('a', 'ff'),
        u'a-natural': ('a', ''),
        u'a-sharp': ('a', 's'),
        u'a-sharpsharp': ('a', 'x'),
        u'af': ('a', 'f'),
        u'aff': ('a', 'ff'),
        u'aqf': ('a', '1qf'),
        u'aqs': ('a', '1qs'),
        u'as': ('a', 's'),
        u'ass': ('a', 'x'),
        u'atqf': ('a', '3qf'),
        u'atqs': ('a', '3qs'),
        u'ax': ('a', 'x'),
        u'b': ('b', ''),
        u'b-flat': ('b', 'f'),
        u'b-flatflat': ('b', 'ff'),
        u'b-natural': ('b', ''),
        u'b-sharp': ('b', 's'),
        u'b-sharpsharp': ('b', 'x'),
        u'bf': ('b', 'f'),
        u'bff': ('b', 'ff'),
        u'bqf': ('b', '1qf'),
        u'bqs': ('b', '1qs'),
        u'bs': ('b', 's'),
        u'bss': ('b', 'x'),
        u'btqf': ('b', '3qf'),
        u'btqs': ('b', '3qs'),
        u'bx': ('b', 'x'),
        u'c': ('c', ''),
        u'c-flat': ('c', 'f'),
        u'c-flatflat': ('c', 'ff'),
        u'c-natural': ('c', ''),
        u'c-sharp': ('c', 's'),
        u'c-sharpsharp': ('c', 'x'),
        u'cf': ('c', 'f'),
        u'cff': ('c', 'ff'),
        u'cqf': ('c', '1qf'),
        u'cqs': ('c', '1qs'),
        u'cs': ('c', 's'),
        u'css': ('c', 'x'),
        u'ctqf': ('c', '3qf'),
        u'ctqs': ('c', '3qs'),
        u'cx': ('c', 'x'),
        u'd': ('d', ''),
        u'd-flat': ('d', 'f'),
        u'd-flatflat': ('d', 'ff'),
        u'd-natural': ('d', ''),
        u'd-sharp': ('d', 's'),
        u'd-sharpsharp': ('d', 'x'),
        u'df': ('d', 'f'),
        u'dff': ('d', 'ff'),
        u'dqf': ('d', '1qf'),
        u'dqs': ('d', '1qs'),
        u'ds': ('d', 's'),
        u'dss': ('d', 'x'),
        u'dtqf': ('d', '3qf'),
        u'dtqs': ('d', '3qs'),
        u'dx': ('d', 'x'),
        u'e': ('e', ''),
        u'e-flat': ('e', 'f'),
        u'e-flatflat': ('e', 'ff'),
        u'e-natural': ('e', ''),
        u'e-sharp': ('e', 's'),
        u'e-sharpsharp': ('e', 'x'),
        u'ef': ('e', 'f'),
        u'eff': ('e', 'ff'),
        u'eqf': ('e', '1qf'),
        u'eqs': ('e', '1qs'),
        u'es': ('e', 's'),
        u'ess': ('e', 'x'),
        u'etqf': ('e', '3qf'),
        u'etqs': ('e', '3qs'),
        u'ex': ('e', 'x'),
        u'f': ('f', ''),
        u'f-flat': ('f', 'f'),
        u'f-flatflat': ('f', 'ff'),
        u'f-natural': ('f', ''),
        u'f-sharp': ('f', 's'),
        u'f-sharpsharp': ('f', 'x'),
        u'ff': ('f', 'f'),
        u'fff': ('f', 'ff'),
        u'fqf': ('f', '1qf'),
        u'fqs': ('f', '1qs'),
        u'fs': ('f', 's'),
        u'fss': ('f', 'x'),
        u'ftqf': ('f', '3qf'),
        u'ftqs': ('f', '3qs'),
        u'fx': ('f', 'x'),
        u'g': ('g', ''),
        u'g-flat': ('g', 'f'),
        u'g-flatflat': ('g', 'ff'),
        u'g-natural': ('g', ''),
        u'g-sharp': ('g', 's'),
        u'g-sharpsharp': ('g', 'x'),
        u'gf': ('g', 'f'),
        u'gff': ('g', 'ff'),
        u'gqf': ('g', '1qf'),
        u'gqs': ('g', '1qs'),
        u'gs': ('g', 's'),
        u'gss': ('g', 'x'),
        u'gtqf': ('g', '3qf'),
        u'gtqs': ('g', '3qs'),
        u'gx': ('g', 'x'),
        },
    u'espanol': {
        u'do': ('c', ''),
        u'dob': ('c', 'f'),
        u'dobb': ('c', 'ff'),
        u'docb': ('c', '1qf'),
        u'docs': ('c', '1qs'),
        u'dos': ('c', 's'),
        u'doss': ('c', 'x'),
        u'dotcb': ('c', '3qf'),
        u'dotcs': ('c', '3qs'),
        u'dox': ('c', 'x'),
        u'fa': ('f', ''),
        u'fab': ('f', 'f'),
        u'fabb': ('f', 'ff'),
        u'facb': ('f', '1qf'),
        u'facs': ('f', '1qs'),
        u'fas': ('f', 's'),
        u'fass': ('f', 'x'),
        u'fatcb': ('f', '3qf'),
        u'fatcs': ('f', '3qs'),
        u'fax': ('f', 'x'),
        u'la': ('a', ''),
        u'lab': ('a', 'f'),
        u'labb': ('a', 'ff'),
        u'lacb': ('a', '1qf'),
        u'lacs': ('a', '1qs'),
        u'las': ('a', 's'),
        u'lass': ('a', 'x'),
        u'latcb': ('a', '3qf'),
        u'latcs': ('a', '3qs'),
        u'lax': ('a', 'x'),
        u'mi': ('e', ''),
        u'mib': ('e', 'f'),
        u'mibb': ('e', 'ff'),
        u'micb': ('e', '1qf'),
        u'mics': ('e', '1qs'),
        u'mis': ('e', 's'),
        u'miss': ('e', 'x'),
        u'mitcb': ('e', '3qf'),
        u'mitcs': ('e', '3qs'),
        u'mix': ('e', 'x'),
        u're': ('d', ''),
        u'reb': ('d', 'f'),
        u'rebb': ('d', 'ff'),
        u'recb': ('d', '1qf'),
        u'recs': ('d', '1qs'),
        u'res': ('d', 's'),
        u'ress': ('d', 'x'),
        u'retcb': ('d', '3qf'),
        u'retcs': ('d', '3qs'),
        u'rex': ('d', 'x'),
        u'si': ('b', ''),
        u'sib': ('b', 'f'),
        u'sibb': ('b', 'ff'),
        u'sicb': ('b', '1qf'),
        u'sics': ('b', '1qs'),
        u'sis': ('b', 's'),
        u'siss': ('b', 'x'),
        u'sitcb': ('b', '3qf'),
        u'sitcs': ('b', '3qs'),
        u'six': ('b', 'x'),
        u'sol': ('g', ''),
        u'solb': ('g', 'f'),
        u'solbb': ('g', 'ff'),
        u'solcb': ('g', '1qf'),
        u'solcs': ('g', '1qs'),
        u'sols': ('g', 's'),
        u'solss': ('g', 'x'),
        u'soltcb': ('g', '3qf'),
        u'soltcs': ('g', '3qs'),
        u'solx': ('g', 'x'),
        },
    u'espa\xf1ol': {
        u'do': ('c', ''),
        u'dob': ('c', 'f'),
        u'dobb': ('c', 'ff'),
        u'docb': ('c', '1qf'),
        u'docs': ('c', '1qs'),
        u'dos': ('c', 's'),
        u'doss': ('c', 'x'),
        u'dotcb': ('c', '3qf'),
        u'dotcs': ('c', '3qs'),
        u'dox': ('c', 'x'),
        u'fa': ('f', ''),
        u'fab': ('f', 'f'),
        u'fabb': ('f', 'ff'),
        u'facb': ('f', '1qf'),
        u'facs': ('f', '1qs'),
        u'fas': ('f', 's'),
        u'fass': ('f', 'x'),
        u'fatcb': ('f', '3qf'),
        u'fatcs': ('f', '3qs'),
        u'fax': ('f', 'x'),
        u'la': ('a', ''),
        u'lab': ('a', 'f'),
        u'labb': ('a', 'ff'),
        u'lacb': ('a', '1qf'),
        u'lacs': ('a', '1qs'),
        u'las': ('a', 's'),
        u'lass': ('a', 'x'),
        u'latcb': ('a', '3qf'),
        u'latcs': ('a', '3qs'),
        u'lax': ('a', 'x'),
        u'mi': ('e', ''),
        u'mib': ('e', 'f'),
        u'mibb': ('e', 'ff'),
        u'micb': ('e', '1qf'),
        u'mics': ('e', '1qs'),
        u'mis': ('e', 's'),
        u'miss': ('e', 'x'),
        u'mitcb': ('e', '3qf'),
        u'mitcs': ('e', '3qs'),
        u'mix': ('e', 'x'),
        u're': ('d', ''),
        u'reb': ('d', 'f'),
        u'rebb': ('d', 'ff'),
        u'recb': ('d', '1qf'),
        u'recs': ('d', '1qs'),
        u'res': ('d', 's'),
        u'ress': ('d', 'x'),
        u'retcb': ('d', '3qf'),
        u'retcs': ('d', '3qs'),
        u'rex': ('d', 'x'),
        u'si': ('b', ''),
        u'sib': ('b', 'f'),
        u'sibb': ('b', 'ff'),
        u'sicb': ('b', '1qf'),
        u'sics': ('b', '1qs'),
        u'sis': ('b', 's'),
        u'siss': ('b', 'x'),
        u'sitcb': ('b', '3qf'),
        u'sitcs': ('b', '3qs'),
        u'six': ('b', 'x'),
        u'sol': ('g', ''),
        u'solb': ('g', 'f'),
        u'solbb': ('g', 'ff'),
        u'solcb': ('g', '1qf'),
        u'solcs': ('g', '1qs'),
        u'sols': ('g', 's'),
        u'solss': ('g', 'x'),
        u'soltcb': ('g', '3qf'),
        u'soltcs': ('g', '3qs'),
        u'solx': ('g', 'x'),
        },
    u'fran\xe7ais': {
        u'do': ('c', ''),
        u'dob': ('c', 'f'),
        u'dobb': ('c', 'ff'),
        u'dobsb': ('c', '3qf'),
        u'dod': ('c', 's'),
        u'dodd': ('c', 'x'),
        u'dodsd': ('c', '3qs'),
        u'dosb': ('c', '1qf'),
        u'dosd': ('c', '1qs'),
        u'dox': ('c', 'x'),
        u'fa': ('f', ''),
        u'fab': ('f', 'f'),
        u'fabb': ('f', 'ff'),
        u'fabsb': ('f', '3qf'),
        u'fad': ('f', 's'),
        u'fadd': ('f', 'x'),
        u'fadsd': ('f', '3qs'),
        u'fasb': ('f', '1qf'),
        u'fasd': ('f', '1qs'),
        u'fax': ('f', 'x'),
        u'la': ('a', ''),
        u'lab': ('a', 'f'),
        u'labb': ('a', 'ff'),
        u'labsb': ('a', '3qf'),
        u'lad': ('a', 's'),
        u'ladd': ('a', 'x'),
        u'ladsd': ('a', '3qs'),
        u'lasb': ('a', '1qf'),
        u'lasd': ('a', '1qs'),
        u'lax': ('a', 'x'),
        u'mi': ('e', ''),
        u'mib': ('e', 'f'),
        u'mibb': ('e', 'ff'),
        u'mibsb': ('e', '3qf'),
        u'mid': ('e', 's'),
        u'midd': ('e', 'x'),
        u'midsd': ('e', '3qs'),
        u'misb': ('e', '1qf'),
        u'misd': ('e', '1qs'),
        u'mix': ('e', 'x'),
        u're': ('d', ''),
        u'reb': ('d', 'f'),
        u'rebb': ('d', 'ff'),
        u'rebsb': ('d', '3qf'),
        u'red': ('d', 's'),
        u'redd': ('d', 'x'),
        u'redsd': ('d', '3qs'),
        u'resb': ('d', '1qf'),
        u'resd': ('d', '1qs'),
        u'rex': ('d', 'x'),
        u'r\xe9': ('d', ''),
        u'r\xe9b': ('d', 'f'),
        u'r\xe9bb': ('d', 'ff'),
        u'r\xe9bsb': ('d', '3qf'),
        u'r\xe9d': ('d', 's'),
        u'r\xe9dd': ('d', 'x'),
        u'r\xe9dsd': ('d', '3qs'),
        u'r\xe9sb': ('d', '1qf'),
        u'r\xe9sd': ('d', '1qs'),
        u'r\xe9x': ('d', 'x'),
        u'si': ('b', ''),
        u'sib': ('b', 'f'),
        u'sibb': ('b', 'ff'),
        u'sibsb': ('b', '3qf'),
        u'sid': ('b', 's'),
        u'sidd': ('b', 'x'),
        u'sidsd': ('b', '3qs'),
        u'sisb': ('b', '1qf'),
        u'sisd': ('b', '1qs'),
        u'six': ('b', 'x'),
        u'sol': ('g', ''),
        u'solb': ('g', 'f'),
        u'solbb': ('g', 'ff'),
        u'solbsb': ('g', '3qf'),
        u'sold': ('g', 's'),
        u'soldd': ('g', 'x'),
        u'soldsd': ('g', '3qs'),
        u'solsb': ('g', '1qf'),
        u'solsd': ('g', '1qs'),
        u'solx': ('g', 'x'),
        },
    u'italiano': {
        u'do': ('c', ''),
        u'dob': ('c', 'f'),
        u'dobb': ('c', 'ff'),
        u'dobsb': ('c', '3qf'),
        u'dod': ('c', 's'),
        u'dodd': ('c', 'x'),
        u'dodsd': ('c', '3qs'),
        u'dosb': ('c', '1qf'),
        u'dosd': ('c', '1qs'),
        u'fa': ('f', ''),
        u'fab': ('f', 'f'),
        u'fabb': ('f', 'ff'),
        u'fabsb': ('f', '3qf'),
        u'fad': ('f', 's'),
        u'fadd': ('f', 'x'),
        u'fadsd': ('f', '3qs'),
        u'fasb': ('f', '1qf'),
        u'fasd': ('f', '1qs'),
        u'la': ('a', ''),
        u'lab': ('a', 'f'),
        u'labb': ('a', 'ff'),
        u'labsb': ('a', '3qf'),
        u'lad': ('a', 's'),
        u'ladd': ('a', 'x'),
        u'ladsd': ('a', '3qs'),
        u'lasb': ('a', '1qf'),
        u'lasd': ('a', '1qs'),
        u'mi': ('e', ''),
        u'mib': ('e', 'f'),
        u'mibb': ('e', 'ff'),
        u'mibsb': ('e', '3qf'),
        u'mid': ('e', 's'),
        u'midd': ('e', 'x'),
        u'midsd': ('e', '3qs'),
        u'misb': ('e', '1qf'),
        u'misd': ('e', '1qs'),
        u're': ('d', ''),
        u'reb': ('d', 'f'),
        u'rebb': ('d', 'ff'),
        u'rebsb': ('d', '3qf'),
        u'red': ('d', 's'),
        u'redd': ('d', 'x'),
        u'redsd': ('d', '3qs'),
        u'resb': ('d', '1qf'),
        u'resd': ('d', '1qs'),
        u'si': ('b', ''),
        u'sib': ('b', 'f'),
        u'sibb': ('b', 'ff'),
        u'sibsb': ('b', '3qf'),
        u'sid': ('b', 's'),
        u'sidd': ('b', 'x'),
        u'sidsd': ('b', '3qs'),
        u'sisb': ('b', '1qf'),
        u'sisd': ('b', '1qs'),
        u'sol': ('g', ''),
        u'solb': ('g', 'f'),
        u'solbb': ('g', 'ff'),
        u'solbsb': ('g', '3qf'),
        u'sold': ('g', 's'),
        u'soldd': ('g', 'x'),
        u'soldsd': ('g', '3qs'),
        u'solsb': ('g', '1qf'),
        u'solsd': ('g', '1qs'),
        },
    u'nederlands': {
        u'a': ('a', ''),
        u'aeh': ('a', '1qf'),
        u'aes': ('a', 'f'),
        u'aeseh': ('a', '3qf'),
        u'aeses': ('a', 'ff'),
        u'aih': ('a', '1qs'),
        u'ais': ('a', 's'),
        u'aisih': ('a', '3qs'),
        u'aisis': ('a', 'x'),
        u'as': ('a', 'f'),
        u'ases': ('a', 'ff'),
        u'b': ('b', ''),
        u'beh': ('b', '1qf'),
        u'bes': ('b', 'f'),
        u'beseh': ('b', '3qf'),
        u'beses': ('b', 'ff'),
        u'bih': ('b', '1qs'),
        u'bis': ('b', 's'),
        u'bisih': ('b', '3qs'),
        u'bisis': ('b', 'x'),
        u'c': ('c', ''),
        u'ceh': ('c', '1qf'),
        u'ces': ('c', 'f'),
        u'ceseh': ('c', '3qf'),
        u'ceses': ('c', 'ff'),
        u'cih': ('c', '1qs'),
        u'cis': ('c', 's'),
        u'cisih': ('c', '3qs'),
        u'cisis': ('c', 'x'),
        u'd': ('d', ''),
        u'deh': ('d', '1qf'),
        u'des': ('d', 'f'),
        u'deseh': ('d', '3qf'),
        u'deses': ('d', 'ff'),
        u'dih': ('d', '1qs'),
        u'dis': ('d', 's'),
        u'disih': ('d', '3qs'),
        u'disis': ('d', 'x'),
        u'e': ('e', ''),
        u'eeh': ('e', '1qf'),
        u'ees': ('e', 'f'),
        u'eeseh': ('e', '3qf'),
        u'eeses': ('e', 'ff'),
        u'eih': ('e', '1qs'),
        u'eis': ('e', 's'),
        u'eisih': ('e', '3qs'),
        u'eisis': ('e', 'x'),
        u'es': ('e', 'f'),
        u'eses': ('e', 'ff'),
        u'f': ('f', ''),
        u'feh': ('f', '1qf'),
        u'fes': ('f', 'f'),
        u'feseh': ('f', '3qf'),
        u'feses': ('f', 'ff'),
        u'fih': ('f', '1qs'),
        u'fis': ('f', 's'),
        u'fisih': ('f', '3qs'),
        u'fisis': ('f', 'x'),
        u'g': ('g', ''),
        u'geh': ('g', '1qf'),
        u'ges': ('g', 'f'),
        u'geseh': ('g', '3qf'),
        u'geses': ('g', 'ff'),
        u'gih': ('g', '1qs'),
        u'gis': ('g', 's'),
        u'gisih': ('g', '3qs'),
        u'gisis': ('g', 'x'),
        },
    u'norsk': {
        u'a': ('a', ''),
        u'aes': ('a', 'f'),
        u'aeses': ('a', 'ff'),
        u'aess': ('a', 'f'),
        u'aessess': ('a', 'ff'),
        u'ais': ('a', 's'),
        u'aisis': ('a', 'x'),
        u'aiss': ('a', 's'),
        u'aississ': ('a', 'x'),
        u'as': ('a', 'f'),
        u'ases': ('a', 'ff'),
        u'ass': ('a', 'f'),
        u'assess': ('a', 'ff'),
        u'b': ('b', 'f'),
        u'bes': ('b', 'ff'),
        u'bess': ('b', 'ff'),
        u'c': ('c', ''),
        u'ces': ('c', 'f'),
        u'ceses': ('c', 'ff'),
        u'cess': ('c', 'f'),
        u'cessess': ('c', 'ff'),
        u'cis': ('c', 's'),
        u'cisis': ('c', 'x'),
        u'ciss': ('c', 's'),
        u'cississ': ('c', 'x'),
        u'd': ('d', ''),
        u'des': ('d', 'f'),
        u'deses': ('d', 'ff'),
        u'dess': ('d', 'f'),
        u'dessess': ('d', 'ff'),
        u'dis': ('d', 's'),
        u'disis': ('d', 'x'),
        u'diss': ('d', 's'),
        u'dississ': ('d', 'x'),
        u'e': ('e', ''),
        u'ees': ('e', 'f'),
        u'eeses': ('e', 'ff'),
        u'eess': ('e', 'f'),
        u'eessess': ('e', 'ff'),
        u'eis': ('e', 's'),
        u'eisis': ('e', 'x'),
        u'eiss': ('e', 's'),
        u'eississ': ('e', 'x'),
        u'es': ('e', 'f'),
        u'eses': ('e', 'ff'),
        u'ess': ('e', 'f'),
        u'essess': ('e', 'ff'),
        u'f': ('f', ''),
        u'fes': ('f', 'f'),
        u'feses': ('f', 'ff'),
        u'fess': ('f', 'f'),
        u'fessess': ('f', 'ff'),
        u'fis': ('f', 's'),
        u'fisis': ('f', 'x'),
        u'fiss': ('f', 's'),
        u'fississ': ('f', 'x'),
        u'g': ('g', ''),
        u'ges': ('g', 'f'),
        u'geses': ('g', 'ff'),
        u'gess': ('g', 'f'),
        u'gessess': ('g', 'ff'),
        u'gis': ('g', 's'),
        u'gisis': ('g', 'x'),
        u'giss': ('g', 's'),
        u'gississ': ('g', 'x'),
        u'h': ('b', ''),
        u'his': ('b', 's'),
        u'hisis': ('b', 'x'),
        u'hiss': ('b', 's'),
        u'hississ': ('b', 'x'),
        },
    u'portugues': {
        u'do': ('c', ''),
        u'dob': ('c', 'f'),
        u'dobb': ('c', 'ff'),
        u'dobqt': ('c', '1qf'),
        u'dobtqt': ('c', '3qf'),
        u'dos': ('c', 's'),
        u'dosqt': ('c', '1qs'),
        u'doss': ('c', 'x'),
        u'dostqt': ('c', '3qs'),
        u'fa': ('f', ''),
        u'fab': ('f', 'f'),
        u'fabb': ('f', 'ff'),
        u'fabqt': ('f', '1qf'),
        u'fabtqt': ('f', '3qf'),
        u'fas': ('f', 's'),
        u'fasqt': ('f', '1qs'),
        u'fass': ('f', 'x'),
        u'fastqt': ('f', '3qs'),
        u'la': ('a', ''),
        u'lab': ('a', 'f'),
        u'labb': ('a', 'ff'),
        u'labqt': ('a', '1qf'),
        u'labtqt': ('a', '3qf'),
        u'las': ('a', 's'),
        u'lasqt': ('a', '1qs'),
        u'lass': ('a', 'x'),
        u'lastqt': ('a', '3qs'),
        u'mi': ('e', ''),
        u'mib': ('e', 'f'),
        u'mibb': ('e', 'ff'),
        u'mibqt': ('e', '1qf'),
        u'mibtqt': ('e', '3qf'),
        u'mis': ('e', 's'),
        u'misqt': ('e', '1qs'),
        u'miss': ('e', 'x'),
        u'mistqt': ('e', '3qs'),
        u're': ('d', ''),
        u'reb': ('d', 'f'),
        u'rebb': ('d', 'ff'),
        u'rebqt': ('d', '1qf'),
        u'rebtqt': ('d', '3qf'),
        u'res': ('d', 's'),
        u'resqt': ('d', '1qs'),
        u'ress': ('d', 'x'),
        u'restqt': ('d', '3qs'),
        u'si': ('b', ''),
        u'sib': ('b', 'f'),
        u'sibb': ('b', 'ff'),
        u'sibqt': ('b', '1qf'),
        u'sibtqt': ('b', '3qf'),
        u'sis': ('b', 's'),
        u'sisqt': ('b', '1qs'),
        u'siss': ('b', 'x'),
        u'sistqt': ('b', '3qs'),
        u'sol': ('g', ''),
        u'solb': ('g', 'f'),
        u'solbb': ('g', 'ff'),
        u'solbqt': ('g', '1qf'),
        u'solbtqt': ('g', '3qf'),
        u'sols': ('g', 's'),
        u'solsqt': ('g', '1qs'),
        u'solss': ('g', 'x'),
        u'solstqt': ('g', '3qs'),
        },
    u'suomi': {
        u'a': ('a', ''),
        u'ais': ('a', 's'),
        u'aisis': ('a', 'x'),
        u'as': ('a', 'f'),
        u'asas': ('a', 'ff'),
        u'ases': ('a', 'ff'),
        u'b': ('b', 'f'),
        u'bb': ('b', 'ff'),
        u'bes': ('b', 'ff'),
        u'c': ('c', ''),
        u'ces': ('c', 'f'),
        u'ceses': ('c', 'ff'),
        u'cis': ('c', 's'),
        u'cisis': ('c', 'x'),
        u'd': ('d', ''),
        u'des': ('d', 'f'),
        u'deses': ('d', 'ff'),
        u'dis': ('d', 's'),
        u'disis': ('d', 'x'),
        u'e': ('e', ''),
        u'eis': ('e', 's'),
        u'eisis': ('e', 'x'),
        u'es': ('e', 'f'),
        u'eses': ('e', 'ff'),
        u'f': ('f', ''),
        u'fes': ('f', 'f'),
        u'feses': ('f', 'ff'),
        u'fis': ('f', 's'),
        u'fisis': ('f', 'x'),
        u'g': ('g', ''),
        u'ges': ('g', 'f'),
        u'geses': ('g', 'ff'),
        u'gis': ('g', 's'),
        u'gisis': ('g', 'x'),
        u'h': ('b', ''),
        u'heses': ('b', 'ff'),
        u'his': ('b', 's'),
        u'hisis': ('b', 'x'),
        },
    u'svenska': {
        u'a': ('a', ''),
        u'aiss': ('a', 's'),
        u'aississ': ('a', 'x'),
        u'ass': ('a', 'f'),
        u'assess': ('a', 'ff'),
        u'b': ('b', 'f'),
        u'c': ('c', ''),
        u'cess': ('c', 'f'),
        u'cessess': ('c', 'ff'),
        u'ciss': ('c', 's'),
        u'cississ': ('c', 'x'),
        u'd': ('d', ''),
        u'dess': ('d', 'f'),
        u'dessess': ('d', 'ff'),
        u'diss': ('d', 's'),
        u'dississ': ('d', 'x'),
        u'e': ('e', ''),
        u'eiss': ('e', 's'),
        u'eississ': ('e', 'x'),
        u'ess': ('e', 'f'),
        u'essess': ('e', 'ff'),
        u'f': ('f', ''),
        u'fess': ('f', 'f'),
        u'fessess': ('f', 'ff'),
        u'fiss': ('f', 's'),
        u'fississ': ('f', 'x'),
        u'g': ('g', ''),
        u'gess': ('g', 'f'),
        u'gessess': ('g', 'ff'),
        u'giss': ('g', 's'),
        u'gississ': ('g', 'x'),
        u'h': ('b', ''),
        u'hessess': ('b', 'ff'),
        u'hiss': ('b', 's'),
        u'hississ': ('b', 'x'),
        },
    u'vlaams': {
        u'do': ('c', ''),
        u'dob': ('c', 'f'),
        u'dobb': ('c', 'ff'),
        u'dok': ('c', 's'),
        u'dokk': ('c', 'x'),
        u'fa': ('f', ''),
        u'fab': ('f', 'f'),
        u'fabb': ('f', 'ff'),
        u'fak': ('f', 's'),
        u'fakk': ('f', 'x'),
        u'la': ('a', ''),
        u'lab': ('a', 'f'),
        u'labb': ('a', 'ff'),
        u'lak': ('a', 's'),
        u'lakk': ('a', 'x'),
        u'mi': ('e', ''),
        u'mib': ('e', 'f'),
        u'mibb': ('e', 'ff'),
        u'mik': ('e', 's'),
        u'mikk': ('e', 'x'),
        u're': ('d', ''),
        u'reb': ('d', 'f'),
        u'rebb': ('d', 'ff'),
        u'rek': ('d', 's'),
        u'rekk': ('d', 'x'),
        u'si': ('b', ''),
        u'sib': ('b', 'f'),
        u'sibb': ('b', 'ff'),
        u'sik': ('b', 's'),
        u'sikk': ('b', 'x'),
        u'sol': ('g', ''),
        u'solb': ('g', 'f'),
        u'solbb': ('g', 'ff'),
        u'solk': ('g', 's'),
        u'solkk': ('g', 'x'),
        },
    }

outbound = {
    u'catalan': {
        'a': u'la',
        'af': u'lab',
        'aff': u'labb',
        'as': u'lad',
        'ax': u'ladd',
        'b': u'si',
        'bf': u'sib',
        'bff': u'sibb',
        'bs': u'sid',
        'bx': u'sidd',
        'c': u'do',
        'cf': u'dob',
        'cff': u'dobb',
        'cs': u'dod',
        'cx': u'dodd',
        'd': u're',
        'df': u'reb',
        'dff': u'rebb',
        'ds': u'red',
        'dx': u'redd',
        'e': u'mi',
        'ef': u'mib',
        'eff': u'mibb',
        'es': u'mid',
        'ex': u'midd',
        'f': u'fa',
        'ff': u'fab',
        'fff': u'fabb',
        'fs': u'fad',
        'fx': u'fadd',
        'g': u'sol',
        'gf': u'solb',
        'gff': u'solbb',
        'gs': u'sold',
        'gx': u'soldd',
        },
    u'deutsch': {
        'a': u'a',
        'a1qf': u'aeh',
        'a1qs': u'aih',
        'a3qf': u'asah',
        'a3qs': u'aisih',
        'af': u'as',
        'aff': u'asas',
        'as': u'ais',
        'ax': u'aisis',
        'b': u'h',
        'b1qf': u'beh',
        'b1qs': u'hih',
        'b3qf': u'heseh',
        'b3qs': u'hisih',
        'bf': u'b',
        'bff': u'heses',
        'bs': u'his',
        'bx': u'hisis',
        'c': u'c',
        'c1qf': u'ceh',
        'c1qs': u'cih',
        'c3qf': u'ceseh',
        'c3qs': u'cisih',
        'cf': u'ces',
        'cff': u'ceses',
        'cs': u'cis',
        'cx': u'cisis',
        'd': u'd',
        'd1qf': u'deh',
        'd1qs': u'dih',
        'd3qf': u'deseh',
        'd3qs': u'disih',
        'df': u'des',
        'dff': u'deses',
        'ds': u'dis',
        'dx': u'disis',
        'e': u'e',
        'e1qf': u'eeh',
        'e1qs': u'eih',
        'e3qf': u'eseh',
        'e3qs': u'eisih',
        'ef': u'es',
        'eff': u'eses',
        'es': u'eis',
        'ex': u'eisis',
        'f': u'f',
        'f1qf': u'feh',
        'f1qs': u'fih',
        'f3qf': u'feseh',
        'f3qs': u'fisih',
        'ff': u'fes',
        'fff': u'feses',
        'fs': u'fis',
        'fx': u'fisis',
        'g': u'g',
        'g1qf': u'geh',
        'g1qs': u'gih',
        'g3qf': u'geseh',
        'g3qs': u'gisih',
        'gf': u'ges',
        'gff': u'geses',
        'gs': u'gis',
        'gx': u'gisis',
        },
    u'english': {
        'a': u'a',
        'a1qf': u'aqf',
        'a1qs': u'aqs',
        'a3qf': u'atqf',
        'a3qs': u'atqs',
        'af': u'af',
        'aff': u'aff',
        'as': u'as',
        'ax': u'ax',
        'b': u'b',
        'b1qf': u'bqf',
        'b1qs': u'bqs',
        'b3qf': u'btqf',
        'b3qs': u'btqs',
        'bf': u'bf',
        'bff': u'bff',
        'bs': u'bs',
        'bx': u'bx',
        'c': u'c',
        'c1qf': u'cqf',
        'c1qs': u'cqs',
        'c3qf': u'ctqf',
        'c3qs': u'ctqs',
        'cf': u'cf',
        'cff': u'cff',
        'cs': u'cs',
        'cx': u'cx',
        'd': u'd',
        'd1qf': u'dqf',
        'd1qs': u'dqs',
        'd3qf': u'dtqf',
        'd3qs': u'dtqs',
        'df': u'df',
        'dff': u'dff',
        'ds': u'ds',
        'dx': u'dx',
        'e': u'e',
        'e1qf': u'eqf',
        'e1qs': u'eqs',
        'e3qf': u'etqf',
        'e3qs': u'etqs',
        'ef': u'ef',
        'eff': u'eff',
        'es': u'es',
        'ex': u'ex',
        'f': u'f',
        'f1qf': u'fqf',
        'f1qs': u'fqs',
        'f3qf': u'ftqf',
        'f3qs': u'ftqs',
        'ff': u'ff',
        'fff': u'fff',
        'fs': u'fs',
        'fx': u'fx',
        'g': u'g',
        'g1qf': u'gqf',
        'g1qs': u'gqs',
        'g3qf': u'gtqf',
        'g3qs': u'gtqs',
        'gf': u'gf',
        'gff': u'gff',
        'gs': u'gs',
        'gx': u'gx',
        },
    u'espanol': {
        'a': u'la',
        'a1qf': u'lacb',
        'a1qs': u'lacs',
        'a3qf': u'latcb',
        'a3qs': u'latcs',
        'af': u'lab',
        'aff': u'labb',
        'as': u'las',
        'ax': u'lax',
        'b': u'si',
        'b1qf': u'sicb',
        'b1qs': u'sics',
        'b3qf': u'sitcb',
        'b3qs': u'sitcs',
        'bf': u'sib',
        'bff': u'sibb',
        'bs': u'sis',
        'bx': u'six',
        'c': u'do',
        'c1qf': u'docb',
        'c1qs': u'docs',
        'c3qf': u'dotcb',
        'c3qs': u'dotcs',
        'cf': u'dob',
        'cff': u'dobb',
        'cs': u'dos',
        'cx': u'dox',
        'd': u're',
        'd1qf': u'recb',
        'd1qs': u'recs',
        'd3qf': u'retcb',
        'd3qs': u'retcs',
        'df': u'reb',
        'dff': u'rebb',
        'ds': u'res',
        'dx': u'rex',
        'e': u'mi',
        'e1qf': u'micb',
        'e1qs': u'mics',
        'e3qf': u'mitcb',
        'e3qs': u'mitcs',
        'ef': u'mib',
        'eff': u'mibb',
        'es': u'mis',
        'ex': u'mix',
        'f': u'fa',
        'f1qf': u'facb',
        'f1qs': u'facs',
        'f3qf': u'fatcb',
        'f3qs': u'fatcs',
        'ff': u'fab',
        'fff': u'fabb',
        'fs': u'fas',
        'fx': u'fax',
        'g': u'sol',
        'g1qf': u'solcb',
        'g1qs': u'solcs',
        'g3qf': u'soltcb',
        'g3qs': u'soltcs',
        'gf': u'solb',
        'gff': u'solbb',
        'gs': u'sols',
        'gx': u'solx',
        },
    u'espa\xf1ol': {
        'a': u'la',
        'a1qf': u'lacb',
        'a1qs': u'lacs',
        'a3qf': u'latcb',
        'a3qs': u'latcs',
        'af': u'lab',
        'aff': u'labb',
        'as': u'las',
        'ax': u'lax',
        'b': u'si',
        'b1qf': u'sicb',
        'b1qs': u'sics',
        'b3qf': u'sitcb',
        'b3qs': u'sitcs',
        'bf': u'sib',
        'bff': u'sibb',
        'bs': u'sis',
        'bx': u'six',
        'c': u'do',
        'c1qf': u'docb',
        'c1qs': u'docs',
        'c3qf': u'dotcb',
        'c3qs': u'dotcs',
        'cf': u'dob',
        'cff': u'dobb',
        'cs': u'dos',
        'cx': u'dox',
        'd': u're',
        'd1qf': u'recb',
        'd1qs': u'recs',
        'd3qf': u'retcb',
        'd3qs': u'retcs',
        'df': u'reb',
        'dff': u'rebb',
        'ds': u'res',
        'dx': u'rex',
        'e': u'mi',
        'e1qf': u'micb',
        'e1qs': u'mics',
        'e3qf': u'mitcb',
        'e3qs': u'mitcs',
        'ef': u'mib',
        'eff': u'mibb',
        'es': u'mis',
        'ex': u'mix',
        'f': u'fa',
        'f1qf': u'facb',
        'f1qs': u'facs',
        'f3qf': u'fatcb',
        'f3qs': u'fatcs',
        'ff': u'fab',
        'fff': u'fabb',
        'fs': u'fas',
        'fx': u'fax',
        'g': u'sol',
        'g1qf': u'solcb',
        'g1qs': u'solcs',
        'g3qf': u'soltcb',
        'g3qs': u'soltcs',
        'gf': u'solb',
        'gff': u'solbb',
        'gs': u'sols',
        'gx': u'solx',
        },
    u'fran\xe7ais': {
        'a': u'la',
        'a1qf': u'lasb',
        'a1qs': u'lasd',
        'a3qf': u'labsb',
        'a3qs': u'ladsd',
        'af': u'lab',
        'aff': u'labb',
        'as': u'lad',
        'ax': u'lax',
        'b': u'si',
        'b1qf': u'sisb',
        'b1qs': u'sisd',
        'b3qf': u'sibsb',
        'b3qs': u'sidsd',
        'bf': u'sib',
        'bff': u'sibb',
        'bs': u'sid',
        'bx': u'six',
        'c': u'do',
        'c1qf': u'dosb',
        'c1qs': u'dosd',
        'c3qf': u'dobsb',
        'c3qs': u'dodsd',
        'cf': u'dob',
        'cff': u'dobb',
        'cs': u'dod',
        'cx': u'dox',
        'd': u'r\xe9',
        'd1qf': u'r\xe9sb',
        'd1qs': u'r\xe9sd',
        'd3qf': u'r\xe9bsb',
        'd3qs': u'r\xe9dsd',
        'df': u'r\xe9b',
        'dff': u'r\xe9bb',
        'ds': u'r\xe9d',
        'dx': u'r\xe9x',
        'e': u'mi',
        'e1qf': u'misb',
        'e1qs': u'misd',
        'e3qf': u'mibsb',
        'e3qs': u'midsd',
        'ef': u'mib',
        'eff': u'mibb',
        'es': u'mid',
        'ex': u'mix',
        'f': u'fa',
        'f1qf': u'fasb',
        'f1qs': u'fasd',
        'f3qf': u'fabsb',
        'f3qs': u'fadsd',
        'ff': u'fab',
        'fff': u'fabb',
        'fs': u'fad',
        'fx': u'fax',
        'g': u'sol',
        'g1qf': u'solsb',
        'g1qs': u'solsd',
        'g3qf': u'solbsb',
        'g3qs': u'soldsd',
        'gf': u'solb',
        'gff': u'solbb',
        'gs': u'sold',
        'gx': u'solx',
        },
    u'italiano': {
        'a': u'la',
        'a1qf': u'lasb',
        'a1qs': u'lasd',
        'a3qf': u'labsb',
        'a3qs': u'ladsd',
        'af': u'lab',
        'aff': u'labb',
        'as': u'lad',
        'ax': u'ladd',
        'b': u'si',
        'b1qf': u'sisb',
        'b1qs': u'sisd',
        'b3qf': u'sibsb',
        'b3qs': u'sidsd',
        'bf': u'sib',
        'bff': u'sibb',
        'bs': u'sid',
        'bx': u'sidd',
        'c': u'do',
        'c1qf': u'dosb',
        'c1qs': u'dosd',
        'c3qf': u'dobsb',
        'c3qs': u'dodsd',
        'cf': u'dob',
        'cff': u'dobb',
        'cs': u'dod',
        'cx': u'dodd',
        'd': u're',
        'd1qf': u'resb',
        'd1qs': u'resd',
        'd3qf': u'rebsb',
        'd3qs': u'redsd',
        'df': u'reb',
        'dff': u'rebb',
        'ds': u'red',
        'dx': u'redd',
        'e': u'mi',
        'e1qf': u'misb',
        'e1qs': u'misd',
        'e3qf': u'mibsb',
        'e3qs': u'midsd',
        'ef': u'mib',
        'eff': u'mibb',
        'es': u'mid',
        'ex': u'midd',
        'f': u'fa',
        'f1qf': u'fasb',
        'f1qs': u'fasd',
        'f3qf': u'fabsb',
        'f3qs': u'fadsd',
        'ff': u'fab',
        'fff': u'fabb',
        'fs': u'fad',
        'fx': u'fadd',
        'g': u'sol',
        'g1qf': u'solsb',
        'g1qs': u'solsd',
        'g3qf': u'solbsb',
        'g3qs': u'soldsd',
        'gf': u'solb',
        'gff': u'solbb',
        'gs': u'sold',
        'gx': u'soldd',
        },
    u'nederlands': {
        'a': u'a',
        'a1qf': u'aeh',
        'a1qs': u'aih',
        'a3qf': u'aeseh',
        'a3qs': u'aisih',
        'af': u'as',
        'aff': u'ases',
        'as': u'ais',
        'ax': u'aisis',
        'b': u'b',
        'b1qf': u'beh',
        'b1qs': u'bih',
        'b3qf': u'beseh',
        'b3qs': u'bisih',
        'bf': u'bes',
        'bff': u'beses',
        'bs': u'bis',
        'bx': u'bisis',
        'c': u'c',
        'c1qf': u'ceh',
        'c1qs': u'cih',
        'c3qf': u'ceseh',
        'c3qs': u'cisih',
        'cf': u'ces',
        'cff': u'ceses',
        'cs': u'cis',
        'cx': u'cisis',
        'd': u'd',
        'd1qf': u'deh',
        'd1qs': u'dih',
        'd3qf': u'deseh',
        'd3qs': u'disih',
        'df': u'des',
        'dff': u'deses',
        'ds': u'dis',
        'dx': u'disis',
        'e': u'e',
        'e1qf': u'eeh',
        'e1qs': u'eih',
        'e3qf': u'eeseh',
        'e3qs': u'eisih',
        'ef': u'es',
        'eff': u'eses',
        'es': u'eis',
        'ex': u'eisis',
        'f': u'f',
        'f1qf': u'feh',
        'f1qs': u'fih',
        'f3qf': u'feseh',
        'f3qs': u'fisih',
        'ff': u'fes',
        'fff': u'feses',
        'fs': u'fis',
        'fx': u'fisis',
        'g': u'g',
        'g1qf': u'geh',
        'g1qs': u'gih',
        'g3qf': u'geseh',
        'g3qs': u'gisih',
        'gf': u'ges',
        'gff': u'geses',
        'gs': u'gis',
        'gx': u'gisis',
        },
    u'norsk': {
        'a': u'a',
        'af': u'as',
        'aff': u'ases',
        'as': u'ais',
        'ax': u'aisis',
        'b': u'h',
        'bf': u'b',
        'bff': u'bes',
        'bs': u'his',
        'bx': u'hisis',
        'c': u'c',
        'cf': u'ces',
        'cff': u'ceses',
        'cs': u'cis',
        'cx': u'cisis',
        'd': u'd',
        'df': u'des',
        'dff': u'deses',
        'ds': u'dis',
        'dx': u'disis',
        'e': u'e',
        'ef': u'es',
        'eff': u'eses',
        'es': u'eis',
        'ex': u'eisis',
        'f': u'f',
        'ff': u'fes',
        'fff': u'feses',
        'fs': u'fis',
        'fx': u'fisis',
        'g': u'g',
        'gf': u'ges',
        'gff': u'geses',
        'gs': u'gis',
        'gx': u'gisis',
        },
    u'portugues': {
        'a': u'la',
        'a1qf': u'labqt',
        'a1qs': u'lasqt',
        'a3qf': u'labtqt',
        'a3qs': u'lastqt',
        'af': u'lab',
        'aff': u'labb',
        'as': u'las',
        'ax': u'lass',
        'b': u'si',
        'b1qf': u'sibqt',
        'b1qs': u'sisqt',
        'b3qf': u'sibtqt',
        'b3qs': u'sistqt',
        'bf': u'sib',
        'bff': u'sibb',
        'bs': u'sis',
        'bx': u'siss',
        'c': u'do',
        'c1qf': u'dobqt',
        'c1qs': u'dosqt',
        'c3qf': u'dobtqt',
        'c3qs': u'dostqt',
        'cf': u'dob',
        'cff': u'dobb',
        'cs': u'dos',
        'cx': u'doss',
        'd': u're',
        'd1qf': u'rebqt',
        'd1qs': u'resqt',
        'd3qf': u'rebtqt',
        'd3qs': u'restqt',
        'df': u'reb',
        'dff': u'rebb',
        'ds': u'res',
        'dx': u'ress',
        'e': u'mi',
        'e1qf': u'mibqt',
        'e1qs': u'misqt',
        'e3qf': u'mibtqt',
        'e3qs': u'mistqt',
        'ef': u'mib',
        'eff': u'mibb',
        'es': u'mis',
        'ex': u'miss',
        'f': u'fa',
        'f1qf': u'fabqt',
        'f1qs': u'fasqt',
        'f3qf': u'fabtqt',
        'f3qs': u'fastqt',
        'ff': u'fab',
        'fff': u'fabb',
        'fs': u'fas',
        'fx': u'fass',
        'g': u'sol',
        'g1qf': u'solbqt',
        'g1qs': u'solsqt',
        'g3qf': u'solbtqt',
        'g3qs': u'solstqt',
        'gf': u'solb',
        'gff': u'solbb',
        'gs': u'sols',
        'gx': u'solss',
        },
    u'suomi': {
        'a': u'a',
        'af': u'as',
        'aff': u'asas',
        'as': u'ais',
        'ax': u'aisis',
        'b': u'h',
        'bf': u'b',
        'bff': u'bb',
        'bs': u'his',
        'bx': u'hisis',
        'c': u'c',
        'cf': u'ces',
        'cff': u'ceses',
        'cs': u'cis',
        'cx': u'cisis',
        'd': u'd',
        'df': u'des',
        'dff': u'deses',
        'ds': u'dis',
        'dx': u'disis',
        'e': u'e',
        'ef': u'es',
        'eff': u'eses',
        'es': u'eis',
        'ex': u'eisis',
        'f': u'f',
        'ff': u'fes',
        'fff': u'feses',
        'fs': u'fis',
        'fx': u'fisis',
        'g': u'g',
        'gf': u'ges',
        'gff': u'geses',
        'gs': u'gis',
        'gx': u'gisis',
        },
    u'svenska': {
        'a': u'a',
        'af': u'ass',
        'aff': u'assess',
        'as': u'aiss',
        'ax': u'aississ',
        'b': u'h',
        'bf': u'b',
        'bff': u'hessess',
        'bs': u'hiss',
        'bx': u'hississ',
        'c': u'c',
        'cf': u'cess',
        'cff': u'cessess',
        'cs': u'ciss',
        'cx': u'cississ',
        'd': u'd',
        'df': u'dess',
        'dff': u'dessess',
        'ds': u'diss',
        'dx': u'dississ',
        'e': u'e',
        'ef': u'ess',
        'eff': u'essess',
        'es': u'eiss',
        'ex': u'eississ',
        'f': u'f',
        'ff': u'fess',
        'fff': u'fessess',
        'fs': u'fiss',
        'fx': u'fississ',
        'g': u'g',
        'gf': u'gess',
        'gff': u'gessess',
        'gs': u'giss',
        'gx': u'gississ',
        },
    u'vlaams': {
        'a': u'la',
        'af': u'lab',
        'aff': u'labb',
        'as': u'lak',
        'ax': u'lakk',
        'b': u'si',
        'bf': u'sib',
        'bff': u'sibb',
        'bs': u'sik',
        'bx': u'sikk',
        'c': u'do',
        'cf': u'dob',
        'cff': u'dobb',
        'cs': u'dok',
        'cx': u'dokk',
        'd': u're',
        'df': u'reb',
        'dff': u'rebb',
        'ds': u'rek',
        'dx': u'rekk',
        'e': u'mi',
        'ef': u'mib',
        'eff': u'mibb',
        'es': u'mik',
        'ex': u'mikk',
        'f': u'fa',
        'ff': u'fab',
        'fff': u'fabb',
        'fs': u'fak',
        'fx': u'fakk',
        'g': u'sol',
        'gf': u'solb',
        'gff': u'solbb',
        'gs': u'solk',
        'gx': u'solkk',
        },
    }
