# -*- coding: utf-8 -*-
'''
Contains dictionaries for translating LilyPond pitch names to
MEI pitch names and back in all languages. This file is generated
by lychee/scripts/make_lilypond_note_names.py.
'''
from __future__ import unicode_literals
inbound = {
    u'catalan': {
        u'do': (u'c', u''),
        u'dob': (u'c', u'f'),
        u'dobb': (u'c', u'ff'),
        u'dod': (u'c', u's'),
        u'dodd': (u'c', u'x'),
        u'dos': (u'c', u's'),
        u'doss': (u'c', u'x'),
        u'fa': (u'f', u''),
        u'fab': (u'f', u'f'),
        u'fabb': (u'f', u'ff'),
        u'fad': (u'f', u's'),
        u'fadd': (u'f', u'x'),
        u'fas': (u'f', u's'),
        u'fass': (u'f', u'x'),
        u'la': (u'a', u''),
        u'lab': (u'a', u'f'),
        u'labb': (u'a', u'ff'),
        u'lad': (u'a', u's'),
        u'ladd': (u'a', u'x'),
        u'las': (u'a', u's'),
        u'lass': (u'a', u'x'),
        u'mi': (u'e', u''),
        u'mib': (u'e', u'f'),
        u'mibb': (u'e', u'ff'),
        u'mid': (u'e', u's'),
        u'midd': (u'e', u'x'),
        u'mis': (u'e', u's'),
        u'miss': (u'e', u'x'),
        u're': (u'd', u''),
        u'reb': (u'd', u'f'),
        u'rebb': (u'd', u'ff'),
        u'red': (u'd', u's'),
        u'redd': (u'd', u'x'),
        u'res': (u'd', u's'),
        u'ress': (u'd', u'x'),
        u'si': (u'b', u''),
        u'sib': (u'b', u'f'),
        u'sibb': (u'b', u'ff'),
        u'sid': (u'b', u's'),
        u'sidd': (u'b', u'x'),
        u'sis': (u'b', u's'),
        u'siss': (u'b', u'x'),
        u'sol': (u'g', u''),
        u'solb': (u'g', u'f'),
        u'solbb': (u'g', u'ff'),
        u'sold': (u'g', u's'),
        u'soldd': (u'g', u'x'),
        u'sols': (u'g', u's'),
        u'solss': (u'g', u'x'),
        },
    u'deutsch': {
        u'a': (u'a', u''),
        u'aeh': (u'a', u'1qf'),
        u'aih': (u'a', u'1qs'),
        u'ais': (u'a', u's'),
        u'aisih': (u'a', u'3qs'),
        u'aisis': (u'a', u'x'),
        u'as': (u'a', u'f'),
        u'asah': (u'a', u'3qf'),
        u'asas': (u'a', u'ff'),
        u'aseh': (u'a', u'3qf'),
        u'ases': (u'a', u'ff'),
        u'b': (u'b', u'f'),
        u'beh': (u'b', u'1qf'),
        u'c': (u'c', u''),
        u'ceh': (u'c', u'1qf'),
        u'ces': (u'c', u'f'),
        u'ceseh': (u'c', u'3qf'),
        u'ceses': (u'c', u'ff'),
        u'cih': (u'c', u'1qs'),
        u'cis': (u'c', u's'),
        u'cisih': (u'c', u'3qs'),
        u'cisis': (u'c', u'x'),
        u'd': (u'd', u''),
        u'deh': (u'd', u'1qf'),
        u'des': (u'd', u'f'),
        u'deseh': (u'd', u'3qf'),
        u'deses': (u'd', u'ff'),
        u'dih': (u'd', u'1qs'),
        u'dis': (u'd', u's'),
        u'disih': (u'd', u'3qs'),
        u'disis': (u'd', u'x'),
        u'e': (u'e', u''),
        u'eeh': (u'e', u'1qf'),
        u'eih': (u'e', u'1qs'),
        u'eis': (u'e', u's'),
        u'eisih': (u'e', u'3qs'),
        u'eisis': (u'e', u'x'),
        u'es': (u'e', u'f'),
        u'eseh': (u'e', u'3qf'),
        u'eses': (u'e', u'ff'),
        u'f': (u'f', u''),
        u'feh': (u'f', u'1qf'),
        u'fes': (u'f', u'f'),
        u'feseh': (u'f', u'3qf'),
        u'feses': (u'f', u'ff'),
        u'fih': (u'f', u'1qs'),
        u'fis': (u'f', u's'),
        u'fisih': (u'f', u'3qs'),
        u'fisis': (u'f', u'x'),
        u'g': (u'g', u''),
        u'geh': (u'g', u'1qf'),
        u'ges': (u'g', u'f'),
        u'geseh': (u'g', u'3qf'),
        u'geses': (u'g', u'ff'),
        u'gih': (u'g', u'1qs'),
        u'gis': (u'g', u's'),
        u'gisih': (u'g', u'3qs'),
        u'gisis': (u'g', u'x'),
        u'h': (u'b', u''),
        u'heseh': (u'b', u'3qf'),
        u'heses': (u'b', u'ff'),
        u'hih': (u'b', u'1qs'),
        u'his': (u'b', u's'),
        u'hisih': (u'b', u'3qs'),
        u'hisis': (u'b', u'x'),
        },
    u'english': {
        u'a': (u'a', u''),
        u'a-flat': (u'a', u'f'),
        u'a-flatflat': (u'a', u'ff'),
        u'a-natural': (u'a', u''),
        u'a-sharp': (u'a', u's'),
        u'a-sharpsharp': (u'a', u'x'),
        u'af': (u'a', u'f'),
        u'aff': (u'a', u'ff'),
        u'aqf': (u'a', u'1qf'),
        u'aqs': (u'a', u'1qs'),
        u'as': (u'a', u's'),
        u'ass': (u'a', u'x'),
        u'atqf': (u'a', u'3qf'),
        u'atqs': (u'a', u'3qs'),
        u'ax': (u'a', u'x'),
        u'b': (u'b', u''),
        u'b-flat': (u'b', u'f'),
        u'b-flatflat': (u'b', u'ff'),
        u'b-natural': (u'b', u''),
        u'b-sharp': (u'b', u's'),
        u'b-sharpsharp': (u'b', u'x'),
        u'bf': (u'b', u'f'),
        u'bff': (u'b', u'ff'),
        u'bqf': (u'b', u'1qf'),
        u'bqs': (u'b', u'1qs'),
        u'bs': (u'b', u's'),
        u'bss': (u'b', u'x'),
        u'btqf': (u'b', u'3qf'),
        u'btqs': (u'b', u'3qs'),
        u'bx': (u'b', u'x'),
        u'c': (u'c', u''),
        u'c-flat': (u'c', u'f'),
        u'c-flatflat': (u'c', u'ff'),
        u'c-natural': (u'c', u''),
        u'c-sharp': (u'c', u's'),
        u'c-sharpsharp': (u'c', u'x'),
        u'cf': (u'c', u'f'),
        u'cff': (u'c', u'ff'),
        u'cqf': (u'c', u'1qf'),
        u'cqs': (u'c', u'1qs'),
        u'cs': (u'c', u's'),
        u'css': (u'c', u'x'),
        u'ctqf': (u'c', u'3qf'),
        u'ctqs': (u'c', u'3qs'),
        u'cx': (u'c', u'x'),
        u'd': (u'd', u''),
        u'd-flat': (u'd', u'f'),
        u'd-flatflat': (u'd', u'ff'),
        u'd-natural': (u'd', u''),
        u'd-sharp': (u'd', u's'),
        u'd-sharpsharp': (u'd', u'x'),
        u'df': (u'd', u'f'),
        u'dff': (u'd', u'ff'),
        u'dqf': (u'd', u'1qf'),
        u'dqs': (u'd', u'1qs'),
        u'ds': (u'd', u's'),
        u'dss': (u'd', u'x'),
        u'dtqf': (u'd', u'3qf'),
        u'dtqs': (u'd', u'3qs'),
        u'dx': (u'd', u'x'),
        u'e': (u'e', u''),
        u'e-flat': (u'e', u'f'),
        u'e-flatflat': (u'e', u'ff'),
        u'e-natural': (u'e', u''),
        u'e-sharp': (u'e', u's'),
        u'e-sharpsharp': (u'e', u'x'),
        u'ef': (u'e', u'f'),
        u'eff': (u'e', u'ff'),
        u'eqf': (u'e', u'1qf'),
        u'eqs': (u'e', u'1qs'),
        u'es': (u'e', u's'),
        u'ess': (u'e', u'x'),
        u'etqf': (u'e', u'3qf'),
        u'etqs': (u'e', u'3qs'),
        u'ex': (u'e', u'x'),
        u'f': (u'f', u''),
        u'f-flat': (u'f', u'f'),
        u'f-flatflat': (u'f', u'ff'),
        u'f-natural': (u'f', u''),
        u'f-sharp': (u'f', u's'),
        u'f-sharpsharp': (u'f', u'x'),
        u'ff': (u'f', u'f'),
        u'fff': (u'f', u'ff'),
        u'fqf': (u'f', u'1qf'),
        u'fqs': (u'f', u'1qs'),
        u'fs': (u'f', u's'),
        u'fss': (u'f', u'x'),
        u'ftqf': (u'f', u'3qf'),
        u'ftqs': (u'f', u'3qs'),
        u'fx': (u'f', u'x'),
        u'g': (u'g', u''),
        u'g-flat': (u'g', u'f'),
        u'g-flatflat': (u'g', u'ff'),
        u'g-natural': (u'g', u''),
        u'g-sharp': (u'g', u's'),
        u'g-sharpsharp': (u'g', u'x'),
        u'gf': (u'g', u'f'),
        u'gff': (u'g', u'ff'),
        u'gqf': (u'g', u'1qf'),
        u'gqs': (u'g', u'1qs'),
        u'gs': (u'g', u's'),
        u'gss': (u'g', u'x'),
        u'gtqf': (u'g', u'3qf'),
        u'gtqs': (u'g', u'3qs'),
        u'gx': (u'g', u'x'),
        },
    u'espanol': {
        u'do': (u'c', u''),
        u'dob': (u'c', u'f'),
        u'dobb': (u'c', u'ff'),
        u'docb': (u'c', u'1qf'),
        u'docs': (u'c', u'1qs'),
        u'dos': (u'c', u's'),
        u'doss': (u'c', u'x'),
        u'dotcb': (u'c', u'3qf'),
        u'dotcs': (u'c', u'3qs'),
        u'dox': (u'c', u'x'),
        u'fa': (u'f', u''),
        u'fab': (u'f', u'f'),
        u'fabb': (u'f', u'ff'),
        u'facb': (u'f', u'1qf'),
        u'facs': (u'f', u'1qs'),
        u'fas': (u'f', u's'),
        u'fass': (u'f', u'x'),
        u'fatcb': (u'f', u'3qf'),
        u'fatcs': (u'f', u'3qs'),
        u'fax': (u'f', u'x'),
        u'la': (u'a', u''),
        u'lab': (u'a', u'f'),
        u'labb': (u'a', u'ff'),
        u'lacb': (u'a', u'1qf'),
        u'lacs': (u'a', u'1qs'),
        u'las': (u'a', u's'),
        u'lass': (u'a', u'x'),
        u'latcb': (u'a', u'3qf'),
        u'latcs': (u'a', u'3qs'),
        u'lax': (u'a', u'x'),
        u'mi': (u'e', u''),
        u'mib': (u'e', u'f'),
        u'mibb': (u'e', u'ff'),
        u'micb': (u'e', u'1qf'),
        u'mics': (u'e', u'1qs'),
        u'mis': (u'e', u's'),
        u'miss': (u'e', u'x'),
        u'mitcb': (u'e', u'3qf'),
        u'mitcs': (u'e', u'3qs'),
        u'mix': (u'e', u'x'),
        u're': (u'd', u''),
        u'reb': (u'd', u'f'),
        u'rebb': (u'd', u'ff'),
        u'recb': (u'd', u'1qf'),
        u'recs': (u'd', u'1qs'),
        u'res': (u'd', u's'),
        u'ress': (u'd', u'x'),
        u'retcb': (u'd', u'3qf'),
        u'retcs': (u'd', u'3qs'),
        u'rex': (u'd', u'x'),
        u'si': (u'b', u''),
        u'sib': (u'b', u'f'),
        u'sibb': (u'b', u'ff'),
        u'sicb': (u'b', u'1qf'),
        u'sics': (u'b', u'1qs'),
        u'sis': (u'b', u's'),
        u'siss': (u'b', u'x'),
        u'sitcb': (u'b', u'3qf'),
        u'sitcs': (u'b', u'3qs'),
        u'six': (u'b', u'x'),
        u'sol': (u'g', u''),
        u'solb': (u'g', u'f'),
        u'solbb': (u'g', u'ff'),
        u'solcb': (u'g', u'1qf'),
        u'solcs': (u'g', u'1qs'),
        u'sols': (u'g', u's'),
        u'solss': (u'g', u'x'),
        u'soltcb': (u'g', u'3qf'),
        u'soltcs': (u'g', u'3qs'),
        u'solx': (u'g', u'x'),
        },
    u'fran\xe7ais': {
        u'do': (u'c', u''),
        u'dob': (u'c', u'f'),
        u'dobb': (u'c', u'ff'),
        u'dobsb': (u'c', u'3qf'),
        u'dod': (u'c', u's'),
        u'dodd': (u'c', u'x'),
        u'dodsd': (u'c', u'3qs'),
        u'dosb': (u'c', u'1qf'),
        u'dosd': (u'c', u'1qs'),
        u'dox': (u'c', u'x'),
        u'fa': (u'f', u''),
        u'fab': (u'f', u'f'),
        u'fabb': (u'f', u'ff'),
        u'fabsb': (u'f', u'3qf'),
        u'fad': (u'f', u's'),
        u'fadd': (u'f', u'x'),
        u'fadsd': (u'f', u'3qs'),
        u'fasb': (u'f', u'1qf'),
        u'fasd': (u'f', u'1qs'),
        u'fax': (u'f', u'x'),
        u'la': (u'a', u''),
        u'lab': (u'a', u'f'),
        u'labb': (u'a', u'ff'),
        u'labsb': (u'a', u'3qf'),
        u'lad': (u'a', u's'),
        u'ladd': (u'a', u'x'),
        u'ladsd': (u'a', u'3qs'),
        u'lasb': (u'a', u'1qf'),
        u'lasd': (u'a', u'1qs'),
        u'lax': (u'a', u'x'),
        u'mi': (u'e', u''),
        u'mib': (u'e', u'f'),
        u'mibb': (u'e', u'ff'),
        u'mibsb': (u'e', u'3qf'),
        u'mid': (u'e', u's'),
        u'midd': (u'e', u'x'),
        u'midsd': (u'e', u'3qs'),
        u'misb': (u'e', u'1qf'),
        u'misd': (u'e', u'1qs'),
        u'mix': (u'e', u'x'),
        u're': (u'd', u''),
        u'reb': (u'd', u'f'),
        u'rebb': (u'd', u'ff'),
        u'rebsb': (u'd', u'3qf'),
        u'red': (u'd', u's'),
        u'redd': (u'd', u'x'),
        u'redsd': (u'd', u'3qs'),
        u'resb': (u'd', u'1qf'),
        u'resd': (u'd', u'1qs'),
        u'rex': (u'd', u'x'),
        u'r\xe9': (u'd', u''),
        u'r\xe9b': (u'd', u'f'),
        u'r\xe9bb': (u'd', u'ff'),
        u'r\xe9bsb': (u'd', u'3qf'),
        u'r\xe9d': (u'd', u's'),
        u'r\xe9dd': (u'd', u'x'),
        u'r\xe9dsd': (u'd', u'3qs'),
        u'r\xe9sb': (u'd', u'1qf'),
        u'r\xe9sd': (u'd', u'1qs'),
        u'r\xe9x': (u'd', u'x'),
        u'si': (u'b', u''),
        u'sib': (u'b', u'f'),
        u'sibb': (u'b', u'ff'),
        u'sibsb': (u'b', u'3qf'),
        u'sid': (u'b', u's'),
        u'sidd': (u'b', u'x'),
        u'sidsd': (u'b', u'3qs'),
        u'sisb': (u'b', u'1qf'),
        u'sisd': (u'b', u'1qs'),
        u'six': (u'b', u'x'),
        u'sol': (u'g', u''),
        u'solb': (u'g', u'f'),
        u'solbb': (u'g', u'ff'),
        u'solbsb': (u'g', u'3qf'),
        u'sold': (u'g', u's'),
        u'soldd': (u'g', u'x'),
        u'soldsd': (u'g', u'3qs'),
        u'solsb': (u'g', u'1qf'),
        u'solsd': (u'g', u'1qs'),
        u'solx': (u'g', u'x'),
        },
    u'italiano': {
        u'do': (u'c', u''),
        u'dob': (u'c', u'f'),
        u'dobb': (u'c', u'ff'),
        u'dobsb': (u'c', u'3qf'),
        u'dod': (u'c', u's'),
        u'dodd': (u'c', u'x'),
        u'dodsd': (u'c', u'3qs'),
        u'dosb': (u'c', u'1qf'),
        u'dosd': (u'c', u'1qs'),
        u'fa': (u'f', u''),
        u'fab': (u'f', u'f'),
        u'fabb': (u'f', u'ff'),
        u'fabsb': (u'f', u'3qf'),
        u'fad': (u'f', u's'),
        u'fadd': (u'f', u'x'),
        u'fadsd': (u'f', u'3qs'),
        u'fasb': (u'f', u'1qf'),
        u'fasd': (u'f', u'1qs'),
        u'la': (u'a', u''),
        u'lab': (u'a', u'f'),
        u'labb': (u'a', u'ff'),
        u'labsb': (u'a', u'3qf'),
        u'lad': (u'a', u's'),
        u'ladd': (u'a', u'x'),
        u'ladsd': (u'a', u'3qs'),
        u'lasb': (u'a', u'1qf'),
        u'lasd': (u'a', u'1qs'),
        u'mi': (u'e', u''),
        u'mib': (u'e', u'f'),
        u'mibb': (u'e', u'ff'),
        u'mibsb': (u'e', u'3qf'),
        u'mid': (u'e', u's'),
        u'midd': (u'e', u'x'),
        u'midsd': (u'e', u'3qs'),
        u'misb': (u'e', u'1qf'),
        u'misd': (u'e', u'1qs'),
        u're': (u'd', u''),
        u'reb': (u'd', u'f'),
        u'rebb': (u'd', u'ff'),
        u'rebsb': (u'd', u'3qf'),
        u'red': (u'd', u's'),
        u'redd': (u'd', u'x'),
        u'redsd': (u'd', u'3qs'),
        u'resb': (u'd', u'1qf'),
        u'resd': (u'd', u'1qs'),
        u'si': (u'b', u''),
        u'sib': (u'b', u'f'),
        u'sibb': (u'b', u'ff'),
        u'sibsb': (u'b', u'3qf'),
        u'sid': (u'b', u's'),
        u'sidd': (u'b', u'x'),
        u'sidsd': (u'b', u'3qs'),
        u'sisb': (u'b', u'1qf'),
        u'sisd': (u'b', u'1qs'),
        u'sol': (u'g', u''),
        u'solb': (u'g', u'f'),
        u'solbb': (u'g', u'ff'),
        u'solbsb': (u'g', u'3qf'),
        u'sold': (u'g', u's'),
        u'soldd': (u'g', u'x'),
        u'soldsd': (u'g', u'3qs'),
        u'solsb': (u'g', u'1qf'),
        u'solsd': (u'g', u'1qs'),
        },
    u'nederlands': {
        u'a': (u'a', u''),
        u'aeh': (u'a', u'1qf'),
        u'aes': (u'a', u'f'),
        u'aeseh': (u'a', u'3qf'),
        u'aeses': (u'a', u'ff'),
        u'aih': (u'a', u'1qs'),
        u'ais': (u'a', u's'),
        u'aisih': (u'a', u'3qs'),
        u'aisis': (u'a', u'x'),
        u'as': (u'a', u'f'),
        u'ases': (u'a', u'ff'),
        u'b': (u'b', u''),
        u'beh': (u'b', u'1qf'),
        u'bes': (u'b', u'f'),
        u'beseh': (u'b', u'3qf'),
        u'beses': (u'b', u'ff'),
        u'bih': (u'b', u'1qs'),
        u'bis': (u'b', u's'),
        u'bisih': (u'b', u'3qs'),
        u'bisis': (u'b', u'x'),
        u'c': (u'c', u''),
        u'ceh': (u'c', u'1qf'),
        u'ces': (u'c', u'f'),
        u'ceseh': (u'c', u'3qf'),
        u'ceses': (u'c', u'ff'),
        u'cih': (u'c', u'1qs'),
        u'cis': (u'c', u's'),
        u'cisih': (u'c', u'3qs'),
        u'cisis': (u'c', u'x'),
        u'd': (u'd', u''),
        u'deh': (u'd', u'1qf'),
        u'des': (u'd', u'f'),
        u'deseh': (u'd', u'3qf'),
        u'deses': (u'd', u'ff'),
        u'dih': (u'd', u'1qs'),
        u'dis': (u'd', u's'),
        u'disih': (u'd', u'3qs'),
        u'disis': (u'd', u'x'),
        u'e': (u'e', u''),
        u'eeh': (u'e', u'1qf'),
        u'ees': (u'e', u'f'),
        u'eeseh': (u'e', u'3qf'),
        u'eeses': (u'e', u'ff'),
        u'eih': (u'e', u'1qs'),
        u'eis': (u'e', u's'),
        u'eisih': (u'e', u'3qs'),
        u'eisis': (u'e', u'x'),
        u'es': (u'e', u'f'),
        u'eses': (u'e', u'ff'),
        u'f': (u'f', u''),
        u'feh': (u'f', u'1qf'),
        u'fes': (u'f', u'f'),
        u'feseh': (u'f', u'3qf'),
        u'feses': (u'f', u'ff'),
        u'fih': (u'f', u'1qs'),
        u'fis': (u'f', u's'),
        u'fisih': (u'f', u'3qs'),
        u'fisis': (u'f', u'x'),
        u'g': (u'g', u''),
        u'geh': (u'g', u'1qf'),
        u'ges': (u'g', u'f'),
        u'geseh': (u'g', u'3qf'),
        u'geses': (u'g', u'ff'),
        u'gih': (u'g', u'1qs'),
        u'gis': (u'g', u's'),
        u'gisih': (u'g', u'3qs'),
        u'gisis': (u'g', u'x'),
        },
    u'norsk': {
        u'a': (u'a', u''),
        u'aes': (u'a', u'f'),
        u'aeses': (u'a', u'ff'),
        u'aess': (u'a', u'f'),
        u'aessess': (u'a', u'ff'),
        u'ais': (u'a', u's'),
        u'aisis': (u'a', u'x'),
        u'aiss': (u'a', u's'),
        u'aississ': (u'a', u'x'),
        u'as': (u'a', u'f'),
        u'ases': (u'a', u'ff'),
        u'ass': (u'a', u'f'),
        u'assess': (u'a', u'ff'),
        u'b': (u'b', u'f'),
        u'bes': (u'b', u'ff'),
        u'bess': (u'b', u'ff'),
        u'c': (u'c', u''),
        u'ces': (u'c', u'f'),
        u'ceses': (u'c', u'ff'),
        u'cess': (u'c', u'f'),
        u'cessess': (u'c', u'ff'),
        u'cis': (u'c', u's'),
        u'cisis': (u'c', u'x'),
        u'ciss': (u'c', u's'),
        u'cississ': (u'c', u'x'),
        u'd': (u'd', u''),
        u'des': (u'd', u'f'),
        u'deses': (u'd', u'ff'),
        u'dess': (u'd', u'f'),
        u'dessess': (u'd', u'ff'),
        u'dis': (u'd', u's'),
        u'disis': (u'd', u'x'),
        u'diss': (u'd', u's'),
        u'dississ': (u'd', u'x'),
        u'e': (u'e', u''),
        u'ees': (u'e', u'f'),
        u'eeses': (u'e', u'ff'),
        u'eess': (u'e', u'f'),
        u'eessess': (u'e', u'ff'),
        u'eis': (u'e', u's'),
        u'eisis': (u'e', u'x'),
        u'eiss': (u'e', u's'),
        u'eississ': (u'e', u'x'),
        u'es': (u'e', u'f'),
        u'eses': (u'e', u'ff'),
        u'ess': (u'e', u'f'),
        u'essess': (u'e', u'ff'),
        u'f': (u'f', u''),
        u'fes': (u'f', u'f'),
        u'feses': (u'f', u'ff'),
        u'fess': (u'f', u'f'),
        u'fessess': (u'f', u'ff'),
        u'fis': (u'f', u's'),
        u'fisis': (u'f', u'x'),
        u'fiss': (u'f', u's'),
        u'fississ': (u'f', u'x'),
        u'g': (u'g', u''),
        u'ges': (u'g', u'f'),
        u'geses': (u'g', u'ff'),
        u'gess': (u'g', u'f'),
        u'gessess': (u'g', u'ff'),
        u'gis': (u'g', u's'),
        u'gisis': (u'g', u'x'),
        u'giss': (u'g', u's'),
        u'gississ': (u'g', u'x'),
        u'h': (u'b', u''),
        u'his': (u'b', u's'),
        u'hisis': (u'b', u'x'),
        u'hiss': (u'b', u's'),
        u'hississ': (u'b', u'x'),
        },
    u'portugues': {
        u'do': (u'c', u''),
        u'dob': (u'c', u'f'),
        u'dobb': (u'c', u'ff'),
        u'dobqt': (u'c', u'1qf'),
        u'dobtqt': (u'c', u'3qf'),
        u'dos': (u'c', u's'),
        u'dosqt': (u'c', u'1qs'),
        u'doss': (u'c', u'x'),
        u'dostqt': (u'c', u'3qs'),
        u'fa': (u'f', u''),
        u'fab': (u'f', u'f'),
        u'fabb': (u'f', u'ff'),
        u'fabqt': (u'f', u'1qf'),
        u'fabtqt': (u'f', u'3qf'),
        u'fas': (u'f', u's'),
        u'fasqt': (u'f', u'1qs'),
        u'fass': (u'f', u'x'),
        u'fastqt': (u'f', u'3qs'),
        u'la': (u'a', u''),
        u'lab': (u'a', u'f'),
        u'labb': (u'a', u'ff'),
        u'labqt': (u'a', u'1qf'),
        u'labtqt': (u'a', u'3qf'),
        u'las': (u'a', u's'),
        u'lasqt': (u'a', u'1qs'),
        u'lass': (u'a', u'x'),
        u'lastqt': (u'a', u'3qs'),
        u'mi': (u'e', u''),
        u'mib': (u'e', u'f'),
        u'mibb': (u'e', u'ff'),
        u'mibqt': (u'e', u'1qf'),
        u'mibtqt': (u'e', u'3qf'),
        u'mis': (u'e', u's'),
        u'misqt': (u'e', u'1qs'),
        u'miss': (u'e', u'x'),
        u'mistqt': (u'e', u'3qs'),
        u're': (u'd', u''),
        u'reb': (u'd', u'f'),
        u'rebb': (u'd', u'ff'),
        u'rebqt': (u'd', u'1qf'),
        u'rebtqt': (u'd', u'3qf'),
        u'res': (u'd', u's'),
        u'resqt': (u'd', u'1qs'),
        u'ress': (u'd', u'x'),
        u'restqt': (u'd', u'3qs'),
        u'si': (u'b', u''),
        u'sib': (u'b', u'f'),
        u'sibb': (u'b', u'ff'),
        u'sibqt': (u'b', u'1qf'),
        u'sibtqt': (u'b', u'3qf'),
        u'sis': (u'b', u's'),
        u'sisqt': (u'b', u'1qs'),
        u'siss': (u'b', u'x'),
        u'sistqt': (u'b', u'3qs'),
        u'sol': (u'g', u''),
        u'solb': (u'g', u'f'),
        u'solbb': (u'g', u'ff'),
        u'solbqt': (u'g', u'1qf'),
        u'solbtqt': (u'g', u'3qf'),
        u'sols': (u'g', u's'),
        u'solsqt': (u'g', u'1qs'),
        u'solss': (u'g', u'x'),
        u'solstqt': (u'g', u'3qs'),
        },
    u'suomi': {
        u'a': (u'a', u''),
        u'ais': (u'a', u's'),
        u'aisis': (u'a', u'x'),
        u'as': (u'a', u'f'),
        u'asas': (u'a', u'ff'),
        u'ases': (u'a', u'ff'),
        u'b': (u'b', u'f'),
        u'bb': (u'b', u'ff'),
        u'bes': (u'b', u'ff'),
        u'c': (u'c', u''),
        u'ces': (u'c', u'f'),
        u'ceses': (u'c', u'ff'),
        u'cis': (u'c', u's'),
        u'cisis': (u'c', u'x'),
        u'd': (u'd', u''),
        u'des': (u'd', u'f'),
        u'deses': (u'd', u'ff'),
        u'dis': (u'd', u's'),
        u'disis': (u'd', u'x'),
        u'e': (u'e', u''),
        u'eis': (u'e', u's'),
        u'eisis': (u'e', u'x'),
        u'es': (u'e', u'f'),
        u'eses': (u'e', u'ff'),
        u'f': (u'f', u''),
        u'fes': (u'f', u'f'),
        u'feses': (u'f', u'ff'),
        u'fis': (u'f', u's'),
        u'fisis': (u'f', u'x'),
        u'g': (u'g', u''),
        u'ges': (u'g', u'f'),
        u'geses': (u'g', u'ff'),
        u'gis': (u'g', u's'),
        u'gisis': (u'g', u'x'),
        u'h': (u'b', u''),
        u'heses': (u'b', u'ff'),
        u'his': (u'b', u's'),
        u'hisis': (u'b', u'x'),
        },
    u'svenska': {
        u'a': (u'a', u''),
        u'aiss': (u'a', u's'),
        u'aississ': (u'a', u'x'),
        u'ass': (u'a', u'f'),
        u'assess': (u'a', u'ff'),
        u'b': (u'b', u'f'),
        u'c': (u'c', u''),
        u'cess': (u'c', u'f'),
        u'cessess': (u'c', u'ff'),
        u'ciss': (u'c', u's'),
        u'cississ': (u'c', u'x'),
        u'd': (u'd', u''),
        u'dess': (u'd', u'f'),
        u'dessess': (u'd', u'ff'),
        u'diss': (u'd', u's'),
        u'dississ': (u'd', u'x'),
        u'e': (u'e', u''),
        u'eiss': (u'e', u's'),
        u'eississ': (u'e', u'x'),
        u'ess': (u'e', u'f'),
        u'essess': (u'e', u'ff'),
        u'f': (u'f', u''),
        u'fess': (u'f', u'f'),
        u'fessess': (u'f', u'ff'),
        u'fiss': (u'f', u's'),
        u'fississ': (u'f', u'x'),
        u'g': (u'g', u''),
        u'gess': (u'g', u'f'),
        u'gessess': (u'g', u'ff'),
        u'giss': (u'g', u's'),
        u'gississ': (u'g', u'x'),
        u'h': (u'b', u''),
        u'hessess': (u'b', u'ff'),
        u'hiss': (u'b', u's'),
        u'hississ': (u'b', u'x'),
        },
    u'vlaams': {
        u'do': (u'c', u''),
        u'dob': (u'c', u'f'),
        u'dobb': (u'c', u'ff'),
        u'dok': (u'c', u's'),
        u'dokk': (u'c', u'x'),
        u'fa': (u'f', u''),
        u'fab': (u'f', u'f'),
        u'fabb': (u'f', u'ff'),
        u'fak': (u'f', u's'),
        u'fakk': (u'f', u'x'),
        u'la': (u'a', u''),
        u'lab': (u'a', u'f'),
        u'labb': (u'a', u'ff'),
        u'lak': (u'a', u's'),
        u'lakk': (u'a', u'x'),
        u'mi': (u'e', u''),
        u'mib': (u'e', u'f'),
        u'mibb': (u'e', u'ff'),
        u'mik': (u'e', u's'),
        u'mikk': (u'e', u'x'),
        u're': (u'd', u''),
        u'reb': (u'd', u'f'),
        u'rebb': (u'd', u'ff'),
        u'rek': (u'd', u's'),
        u'rekk': (u'd', u'x'),
        u'si': (u'b', u''),
        u'sib': (u'b', u'f'),
        u'sibb': (u'b', u'ff'),
        u'sik': (u'b', u's'),
        u'sikk': (u'b', u'x'),
        u'sol': (u'g', u''),
        u'solb': (u'g', u'f'),
        u'solbb': (u'g', u'ff'),
        u'solk': (u'g', u's'),
        u'solkk': (u'g', u'x'),
        },
    }

outbound = {
    u'catalan': {
        u'a': u'la',
        u'af': u'lab',
        u'aff': u'labb',
        u'as': u'lad',
        u'ax': u'ladd',
        u'b': u'si',
        u'bf': u'sib',
        u'bff': u'sibb',
        u'bs': u'sid',
        u'bx': u'sidd',
        u'c': u'do',
        u'cf': u'dob',
        u'cff': u'dobb',
        u'cs': u'dod',
        u'cx': u'dodd',
        u'd': u're',
        u'df': u'reb',
        u'dff': u'rebb',
        u'ds': u'red',
        u'dx': u'redd',
        u'e': u'mi',
        u'ef': u'mib',
        u'eff': u'mibb',
        u'es': u'mid',
        u'ex': u'midd',
        u'f': u'fa',
        u'ff': u'fab',
        u'fff': u'fabb',
        u'fs': u'fad',
        u'fx': u'fadd',
        u'g': u'sol',
        u'gf': u'solb',
        u'gff': u'solbb',
        u'gs': u'sold',
        u'gx': u'soldd',
        },
    u'deutsch': {
        u'a': u'a',
        u'a1qf': u'aeh',
        u'a1qs': u'aih',
        u'a3qf': u'asah',
        u'a3qs': u'aisih',
        u'af': u'as',
        u'aff': u'asas',
        u'as': u'ais',
        u'ax': u'aisis',
        u'b': u'h',
        u'b1qf': u'beh',
        u'b1qs': u'hih',
        u'b3qf': u'heseh',
        u'b3qs': u'hisih',
        u'bf': u'b',
        u'bff': u'heses',
        u'bs': u'his',
        u'bx': u'hisis',
        u'c': u'c',
        u'c1qf': u'ceh',
        u'c1qs': u'cih',
        u'c3qf': u'ceseh',
        u'c3qs': u'cisih',
        u'cf': u'ces',
        u'cff': u'ceses',
        u'cs': u'cis',
        u'cx': u'cisis',
        u'd': u'd',
        u'd1qf': u'deh',
        u'd1qs': u'dih',
        u'd3qf': u'deseh',
        u'd3qs': u'disih',
        u'df': u'des',
        u'dff': u'deses',
        u'ds': u'dis',
        u'dx': u'disis',
        u'e': u'e',
        u'e1qf': u'eeh',
        u'e1qs': u'eih',
        u'e3qf': u'eseh',
        u'e3qs': u'eisih',
        u'ef': u'es',
        u'eff': u'eses',
        u'es': u'eis',
        u'ex': u'eisis',
        u'f': u'f',
        u'f1qf': u'feh',
        u'f1qs': u'fih',
        u'f3qf': u'feseh',
        u'f3qs': u'fisih',
        u'ff': u'fes',
        u'fff': u'feses',
        u'fs': u'fis',
        u'fx': u'fisis',
        u'g': u'g',
        u'g1qf': u'geh',
        u'g1qs': u'gih',
        u'g3qf': u'geseh',
        u'g3qs': u'gisih',
        u'gf': u'ges',
        u'gff': u'geses',
        u'gs': u'gis',
        u'gx': u'gisis',
        },
    u'english': {
        u'a': u'a',
        u'a1qf': u'aqf',
        u'a1qs': u'aqs',
        u'a3qf': u'atqf',
        u'a3qs': u'atqs',
        u'af': u'af',
        u'aff': u'aff',
        u'as': u'as',
        u'ax': u'ax',
        u'b': u'b',
        u'b1qf': u'bqf',
        u'b1qs': u'bqs',
        u'b3qf': u'btqf',
        u'b3qs': u'btqs',
        u'bf': u'bf',
        u'bff': u'bff',
        u'bs': u'bs',
        u'bx': u'bx',
        u'c': u'c',
        u'c1qf': u'cqf',
        u'c1qs': u'cqs',
        u'c3qf': u'ctqf',
        u'c3qs': u'ctqs',
        u'cf': u'cf',
        u'cff': u'cff',
        u'cs': u'cs',
        u'cx': u'cx',
        u'd': u'd',
        u'd1qf': u'dqf',
        u'd1qs': u'dqs',
        u'd3qf': u'dtqf',
        u'd3qs': u'dtqs',
        u'df': u'df',
        u'dff': u'dff',
        u'ds': u'ds',
        u'dx': u'dx',
        u'e': u'e',
        u'e1qf': u'eqf',
        u'e1qs': u'eqs',
        u'e3qf': u'etqf',
        u'e3qs': u'etqs',
        u'ef': u'ef',
        u'eff': u'eff',
        u'es': u'es',
        u'ex': u'ex',
        u'f': u'f',
        u'f1qf': u'fqf',
        u'f1qs': u'fqs',
        u'f3qf': u'ftqf',
        u'f3qs': u'ftqs',
        u'ff': u'ff',
        u'fff': u'fff',
        u'fs': u'fs',
        u'fx': u'fx',
        u'g': u'g',
        u'g1qf': u'gqf',
        u'g1qs': u'gqs',
        u'g3qf': u'gtqf',
        u'g3qs': u'gtqs',
        u'gf': u'gf',
        u'gff': u'gff',
        u'gs': u'gs',
        u'gx': u'gx',
        },
    u'espanol': {
        u'a': u'la',
        u'a1qf': u'lacb',
        u'a1qs': u'lacs',
        u'a3qf': u'latcb',
        u'a3qs': u'latcs',
        u'af': u'lab',
        u'aff': u'labb',
        u'as': u'las',
        u'ax': u'lax',
        u'b': u'si',
        u'b1qf': u'sicb',
        u'b1qs': u'sics',
        u'b3qf': u'sitcb',
        u'b3qs': u'sitcs',
        u'bf': u'sib',
        u'bff': u'sibb',
        u'bs': u'sis',
        u'bx': u'six',
        u'c': u'do',
        u'c1qf': u'docb',
        u'c1qs': u'docs',
        u'c3qf': u'dotcb',
        u'c3qs': u'dotcs',
        u'cf': u'dob',
        u'cff': u'dobb',
        u'cs': u'dos',
        u'cx': u'dox',
        u'd': u're',
        u'd1qf': u'recb',
        u'd1qs': u'recs',
        u'd3qf': u'retcb',
        u'd3qs': u'retcs',
        u'df': u'reb',
        u'dff': u'rebb',
        u'ds': u'res',
        u'dx': u'rex',
        u'e': u'mi',
        u'e1qf': u'micb',
        u'e1qs': u'mics',
        u'e3qf': u'mitcb',
        u'e3qs': u'mitcs',
        u'ef': u'mib',
        u'eff': u'mibb',
        u'es': u'mis',
        u'ex': u'mix',
        u'f': u'fa',
        u'f1qf': u'facb',
        u'f1qs': u'facs',
        u'f3qf': u'fatcb',
        u'f3qs': u'fatcs',
        u'ff': u'fab',
        u'fff': u'fabb',
        u'fs': u'fas',
        u'fx': u'fax',
        u'g': u'sol',
        u'g1qf': u'solcb',
        u'g1qs': u'solcs',
        u'g3qf': u'soltcb',
        u'g3qs': u'soltcs',
        u'gf': u'solb',
        u'gff': u'solbb',
        u'gs': u'sols',
        u'gx': u'solx',
        },
    u'fran\xe7ais': {
        u'a': u'la',
        u'a1qf': u'lasb',
        u'a1qs': u'lasd',
        u'a3qf': u'labsb',
        u'a3qs': u'ladsd',
        u'af': u'lab',
        u'aff': u'labb',
        u'as': u'lad',
        u'ax': u'lax',
        u'b': u'si',
        u'b1qf': u'sisb',
        u'b1qs': u'sisd',
        u'b3qf': u'sibsb',
        u'b3qs': u'sidsd',
        u'bf': u'sib',
        u'bff': u'sibb',
        u'bs': u'sid',
        u'bx': u'six',
        u'c': u'do',
        u'c1qf': u'dosb',
        u'c1qs': u'dosd',
        u'c3qf': u'dobsb',
        u'c3qs': u'dodsd',
        u'cf': u'dob',
        u'cff': u'dobb',
        u'cs': u'dod',
        u'cx': u'dox',
        u'd': u'r\xe9',
        u'd1qf': u'r\xe9sb',
        u'd1qs': u'r\xe9sd',
        u'd3qf': u'r\xe9bsb',
        u'd3qs': u'r\xe9dsd',
        u'df': u'r\xe9b',
        u'dff': u'r\xe9bb',
        u'ds': u'r\xe9d',
        u'dx': u'r\xe9x',
        u'e': u'mi',
        u'e1qf': u'misb',
        u'e1qs': u'misd',
        u'e3qf': u'mibsb',
        u'e3qs': u'midsd',
        u'ef': u'mib',
        u'eff': u'mibb',
        u'es': u'mid',
        u'ex': u'mix',
        u'f': u'fa',
        u'f1qf': u'fasb',
        u'f1qs': u'fasd',
        u'f3qf': u'fabsb',
        u'f3qs': u'fadsd',
        u'ff': u'fab',
        u'fff': u'fabb',
        u'fs': u'fad',
        u'fx': u'fax',
        u'g': u'sol',
        u'g1qf': u'solsb',
        u'g1qs': u'solsd',
        u'g3qf': u'solbsb',
        u'g3qs': u'soldsd',
        u'gf': u'solb',
        u'gff': u'solbb',
        u'gs': u'sold',
        u'gx': u'solx',
        },
    u'italiano': {
        u'a': u'la',
        u'a1qf': u'lasb',
        u'a1qs': u'lasd',
        u'a3qf': u'labsb',
        u'a3qs': u'ladsd',
        u'af': u'lab',
        u'aff': u'labb',
        u'as': u'lad',
        u'ax': u'ladd',
        u'b': u'si',
        u'b1qf': u'sisb',
        u'b1qs': u'sisd',
        u'b3qf': u'sibsb',
        u'b3qs': u'sidsd',
        u'bf': u'sib',
        u'bff': u'sibb',
        u'bs': u'sid',
        u'bx': u'sidd',
        u'c': u'do',
        u'c1qf': u'dosb',
        u'c1qs': u'dosd',
        u'c3qf': u'dobsb',
        u'c3qs': u'dodsd',
        u'cf': u'dob',
        u'cff': u'dobb',
        u'cs': u'dod',
        u'cx': u'dodd',
        u'd': u're',
        u'd1qf': u'resb',
        u'd1qs': u'resd',
        u'd3qf': u'rebsb',
        u'd3qs': u'redsd',
        u'df': u'reb',
        u'dff': u'rebb',
        u'ds': u'red',
        u'dx': u'redd',
        u'e': u'mi',
        u'e1qf': u'misb',
        u'e1qs': u'misd',
        u'e3qf': u'mibsb',
        u'e3qs': u'midsd',
        u'ef': u'mib',
        u'eff': u'mibb',
        u'es': u'mid',
        u'ex': u'midd',
        u'f': u'fa',
        u'f1qf': u'fasb',
        u'f1qs': u'fasd',
        u'f3qf': u'fabsb',
        u'f3qs': u'fadsd',
        u'ff': u'fab',
        u'fff': u'fabb',
        u'fs': u'fad',
        u'fx': u'fadd',
        u'g': u'sol',
        u'g1qf': u'solsb',
        u'g1qs': u'solsd',
        u'g3qf': u'solbsb',
        u'g3qs': u'soldsd',
        u'gf': u'solb',
        u'gff': u'solbb',
        u'gs': u'sold',
        u'gx': u'soldd',
        },
    u'nederlands': {
        u'a': u'a',
        u'a1qf': u'aeh',
        u'a1qs': u'aih',
        u'a3qf': u'aeseh',
        u'a3qs': u'aisih',
        u'af': u'as',
        u'aff': u'ases',
        u'as': u'ais',
        u'ax': u'aisis',
        u'b': u'b',
        u'b1qf': u'beh',
        u'b1qs': u'bih',
        u'b3qf': u'beseh',
        u'b3qs': u'bisih',
        u'bf': u'bes',
        u'bff': u'beses',
        u'bs': u'bis',
        u'bx': u'bisis',
        u'c': u'c',
        u'c1qf': u'ceh',
        u'c1qs': u'cih',
        u'c3qf': u'ceseh',
        u'c3qs': u'cisih',
        u'cf': u'ces',
        u'cff': u'ceses',
        u'cs': u'cis',
        u'cx': u'cisis',
        u'd': u'd',
        u'd1qf': u'deh',
        u'd1qs': u'dih',
        u'd3qf': u'deseh',
        u'd3qs': u'disih',
        u'df': u'des',
        u'dff': u'deses',
        u'ds': u'dis',
        u'dx': u'disis',
        u'e': u'e',
        u'e1qf': u'eeh',
        u'e1qs': u'eih',
        u'e3qf': u'eeseh',
        u'e3qs': u'eisih',
        u'ef': u'es',
        u'eff': u'eses',
        u'es': u'eis',
        u'ex': u'eisis',
        u'f': u'f',
        u'f1qf': u'feh',
        u'f1qs': u'fih',
        u'f3qf': u'feseh',
        u'f3qs': u'fisih',
        u'ff': u'fes',
        u'fff': u'feses',
        u'fs': u'fis',
        u'fx': u'fisis',
        u'g': u'g',
        u'g1qf': u'geh',
        u'g1qs': u'gih',
        u'g3qf': u'geseh',
        u'g3qs': u'gisih',
        u'gf': u'ges',
        u'gff': u'geses',
        u'gs': u'gis',
        u'gx': u'gisis',
        },
    u'norsk': {
        u'a': u'a',
        u'af': u'as',
        u'aff': u'ases',
        u'as': u'ais',
        u'ax': u'aisis',
        u'b': u'h',
        u'bf': u'b',
        u'bff': u'bes',
        u'bs': u'his',
        u'bx': u'hisis',
        u'c': u'c',
        u'cf': u'ces',
        u'cff': u'ceses',
        u'cs': u'cis',
        u'cx': u'cisis',
        u'd': u'd',
        u'df': u'des',
        u'dff': u'deses',
        u'ds': u'dis',
        u'dx': u'disis',
        u'e': u'e',
        u'ef': u'es',
        u'eff': u'eses',
        u'es': u'eis',
        u'ex': u'eisis',
        u'f': u'f',
        u'ff': u'fes',
        u'fff': u'feses',
        u'fs': u'fis',
        u'fx': u'fisis',
        u'g': u'g',
        u'gf': u'ges',
        u'gff': u'geses',
        u'gs': u'gis',
        u'gx': u'gisis',
        },
    u'portugues': {
        u'a': u'la',
        u'a1qf': u'labqt',
        u'a1qs': u'lasqt',
        u'a3qf': u'labtqt',
        u'a3qs': u'lastqt',
        u'af': u'lab',
        u'aff': u'labb',
        u'as': u'las',
        u'ax': u'lass',
        u'b': u'si',
        u'b1qf': u'sibqt',
        u'b1qs': u'sisqt',
        u'b3qf': u'sibtqt',
        u'b3qs': u'sistqt',
        u'bf': u'sib',
        u'bff': u'sibb',
        u'bs': u'sis',
        u'bx': u'siss',
        u'c': u'do',
        u'c1qf': u'dobqt',
        u'c1qs': u'dosqt',
        u'c3qf': u'dobtqt',
        u'c3qs': u'dostqt',
        u'cf': u'dob',
        u'cff': u'dobb',
        u'cs': u'dos',
        u'cx': u'doss',
        u'd': u're',
        u'd1qf': u'rebqt',
        u'd1qs': u'resqt',
        u'd3qf': u'rebtqt',
        u'd3qs': u'restqt',
        u'df': u'reb',
        u'dff': u'rebb',
        u'ds': u'res',
        u'dx': u'ress',
        u'e': u'mi',
        u'e1qf': u'mibqt',
        u'e1qs': u'misqt',
        u'e3qf': u'mibtqt',
        u'e3qs': u'mistqt',
        u'ef': u'mib',
        u'eff': u'mibb',
        u'es': u'mis',
        u'ex': u'miss',
        u'f': u'fa',
        u'f1qf': u'fabqt',
        u'f1qs': u'fasqt',
        u'f3qf': u'fabtqt',
        u'f3qs': u'fastqt',
        u'ff': u'fab',
        u'fff': u'fabb',
        u'fs': u'fas',
        u'fx': u'fass',
        u'g': u'sol',
        u'g1qf': u'solbqt',
        u'g1qs': u'solsqt',
        u'g3qf': u'solbtqt',
        u'g3qs': u'solstqt',
        u'gf': u'solb',
        u'gff': u'solbb',
        u'gs': u'sols',
        u'gx': u'solss',
        },
    u'suomi': {
        u'a': u'a',
        u'af': u'as',
        u'aff': u'asas',
        u'as': u'ais',
        u'ax': u'aisis',
        u'b': u'h',
        u'bf': u'b',
        u'bff': u'bb',
        u'bs': u'his',
        u'bx': u'hisis',
        u'c': u'c',
        u'cf': u'ces',
        u'cff': u'ceses',
        u'cs': u'cis',
        u'cx': u'cisis',
        u'd': u'd',
        u'df': u'des',
        u'dff': u'deses',
        u'ds': u'dis',
        u'dx': u'disis',
        u'e': u'e',
        u'ef': u'es',
        u'eff': u'eses',
        u'es': u'eis',
        u'ex': u'eisis',
        u'f': u'f',
        u'ff': u'fes',
        u'fff': u'feses',
        u'fs': u'fis',
        u'fx': u'fisis',
        u'g': u'g',
        u'gf': u'ges',
        u'gff': u'geses',
        u'gs': u'gis',
        u'gx': u'gisis',
        },
    u'svenska': {
        u'a': u'a',
        u'af': u'ass',
        u'aff': u'assess',
        u'as': u'aiss',
        u'ax': u'aississ',
        u'b': u'h',
        u'bf': u'b',
        u'bff': u'hessess',
        u'bs': u'hiss',
        u'bx': u'hississ',
        u'c': u'c',
        u'cf': u'cess',
        u'cff': u'cessess',
        u'cs': u'ciss',
        u'cx': u'cississ',
        u'd': u'd',
        u'df': u'dess',
        u'dff': u'dessess',
        u'ds': u'diss',
        u'dx': u'dississ',
        u'e': u'e',
        u'ef': u'ess',
        u'eff': u'essess',
        u'es': u'eiss',
        u'ex': u'eississ',
        u'f': u'f',
        u'ff': u'fess',
        u'fff': u'fessess',
        u'fs': u'fiss',
        u'fx': u'fississ',
        u'g': u'g',
        u'gf': u'gess',
        u'gff': u'gessess',
        u'gs': u'giss',
        u'gx': u'gississ',
        },
    u'vlaams': {
        u'a': u'la',
        u'af': u'lab',
        u'aff': u'labb',
        u'as': u'lak',
        u'ax': u'lakk',
        u'b': u'si',
        u'bf': u'sib',
        u'bff': u'sibb',
        u'bs': u'sik',
        u'bx': u'sikk',
        u'c': u'do',
        u'cf': u'dob',
        u'cff': u'dobb',
        u'cs': u'dok',
        u'cx': u'dokk',
        u'd': u're',
        u'df': u'reb',
        u'dff': u'rebb',
        u'ds': u'rek',
        u'dx': u'rekk',
        u'e': u'mi',
        u'ef': u'mib',
        u'eff': u'mibb',
        u'es': u'mik',
        u'ex': u'mikk',
        u'f': u'fa',
        u'ff': u'fab',
        u'fff': u'fabb',
        u'fs': u'fak',
        u'fx': u'fakk',
        u'g': u'sol',
        u'gf': u'solb',
        u'gff': u'solbb',
        u'gs': u'solk',
        u'gx': u'solkk',
        },
    }
inbound['español'] = inbound['espanol']
outbound['español'] = outbound['espanol']
